#!/bin/sh
# List a directory on an archival system
# Arguments:
# 1 local file that has list
#
if [ $# -ne 1 ] ; then
  echo "Usage: archive_list local_list - REQUIRED"
  ./procstat.sh error archive_list
  exit 1
else
  ARCHIVE_L=$1
fi
#
# If hsi command exists, use it.
#
TEST4HSI=`which hsi 2<&1`
if [ $? -eq 0 ] ; then
  PROCHOST=`hostname`;export PROCHOST
  case "$PROCHOST" in 
    modeling1* )  # Funny bash implementation of hsi 
      HSI="hsi -s nocache" ;;
    * )           # Everywhere else
      HSI="hsi -q" ;;
  esac
  echo "HSI command: "${HSI}
#
  $HSI "ls -Fl $ARCHIVE_HIST" 2>&1 | egrep "\.${HIST}\." | cut -c60- > $ARCHIVE_L 2>&1 
  if [ $? -ne 0 ] ; then
    echo "Error on archive_list from "$ARCHIVE_HIST
    ./procstat.sh error archive_list
    exit 1
  fi
else
  echo "Cannot find hsi command."
  ./procstat.sh error archive_list
  exit 1
fi
