#!/bin/sh
# Write a file to a mass store
#
# Arguments:
# 1 directory on archival system to write file to
#
if [ $# = 1 ] ; then
  ARCHIVE_D=$1
else
  echo "I need an arguments:"
  echo "Directory on archival system to write file to"
  ./status_check error archive_write
  exit 1
fi
#
# If hsi command exists, use it.
#
TEST4HSI=`which hsi 2<&1`
if [ $? -eq 0 ] ; then
  $HSI "mkdir -p $ARCHIVE_D"
  $HSI "chmod 775 $ARCHIVE_D"
  $HSI << EOF
cd $ARCHIVE_D
put -U *.nc
chmod 644 *nc
EOF
  if [ $? -eq 0 ] ; then
    echo "Files written to "${ARCHIVE_D}" and erased."
  else
    $HSI "put *.nc"
    if [ $? -eq 0 ] ; then
      echo "Files written to your HPSS HOME and erased."
    else
      echo "Problem with HPSS on write. Stopping"
	./status_check error archive_write
      exit 1
    fi
  fi      
else
  echo "Cannot find hsi command."
  ./status_check error archive_write
  exit 1
fi
