#!/bin/sh
# Read file(s) from a archival system
#
if [ $# -ne 3 ] ; then
  echo "Usage: archive_read $CASE $HIST $LOCAL_HIST"
  echo "Requires $CASE $HIST and $LOCAL_HIST"
  echo "CASE HIST LOCAL_HIST must be defined"
  ./procstat.sh error archive_read
  exit 1
else
  CASE=$1
  HIST=$2
  LOCL=$3
fi
if [ ! $CASE ] ; then
  echo "archive_read: CASE undefined. Exit."
fi
if [ ! $HIST ] ; then
  echo "archive_read: HIST undefined. Exit."
fi
if [ ! $LOCL ] ; then
  echo "archive_read: LOCAL_HIST undefined. Exit."
fi
#
# If hsi command exists, use it.
#
TEST4HSI=`which hsi 2<&1`
if [ $? -eq 0 ] ; then
  PROCHOST=`hostname`;export PROCHOST
  case "$PROCHOST" in 
    modeling1* )  # Funny bash implementation of hsi 
      HSI="hsi -s nocache" ;;
    * )           # Everywhere else
      HSI="hsi -q" ;;
  esac
  echo "HSI command: "${HSI}
#
  $HSI "cget -u ${ARCHIVE_HIST}/${CASE}.${HIST}.${YEARNOW}*"
  if [ $? -ne 0 ] ; then
    echo "Error on hsi get of "$ARCHIVE_HIST"/"$ARCHIVE_FILES
    ./procstat.sh error archive_read
    exit 1
  fi
else
  echo "Cannot find hsi command."
  ./procstat.sh error archive_read
  exit 1
fi
