#!/bin/csh -f
#
# Concatenate months of IPCC netCDF files into years
#
if ("$#argv" != 0) then
   echo "Usage: cf_var_ann_concat"
   exit 1
endif
#
set vars   = `ls | egrep '\.nc$' | cut -d"_" -f1 | uniq`
if ($status == 0) then
  set table  = `ls | egrep '\.nc$' | cut -d"_" -f2 | cut -d"." -f1 | sort | uniq`
  set expids = `ls | egrep '\.nc$' | cut -d"." -f2 | sort | uniq`
  set model  = `ls | egrep '\.nc$' | cut -d"." -f3 | sort | uniq`
  set comp   = `ls | egrep '\.nc$' | cut -d"." -f4 | sort | uniq`
  set years  = `ls | egrep '\.nc$' | cut -d"." -f5 | cut -c1-4 | sort | uniq`
#
  foreach v (${vars})
    foreach t (${table})
      foreach e (${expids})
        foreach y (${years})
          foreach m (${model})
            foreach c (${comp})
              if (-f ${v}_${t}.${e}.${m}.${c}.${y}-12.nc) then
                set num = `ls ${v}_${t}.${e}.${m}.${c}.${y}-??.nc | wc -l`
                if (${num} == 12) then
                  set df = ${v}_${t}.${e}.${m}.${c}.${y}.nc
                  ncrcat -h -O ${v}_${t}.${e}.${m}.${c}.${y}-??.nc ${df}
                  if ($status == 0) then
                    rm -f ${v}_${t}.${e}.${m}.{$c}.${y}-??.nc
                    echo "Completed "${df}
                  endif
                endif
              endif
            end
          end
        end
      end
    end
  end
endif
#
exit
