#!/bin/sh
#
# Concatenate years of IPCC netCDF files into decades
#
if [ $# -ne 0 ] ; then
   echo "Usage: cf_var_dec_concat"
   exit 1
fi
# 
# Check for ncrcat
#
if [ ! $NCRCAT ] ; then
   TEST4NCRCAT=`which ncrcat 2<&1 >& /dev/null`
   if [ $? -eq 0 ] ; then
     NCRCAT=`which ncrcat`
   else
     echo "NCRCAT not in PATH - UNDEFINED"
     exit 1
   fi
fi
#
VARS=`ls | egrep '\....._c......\.nc$' | cut -d"_" -f1 | uniq`
for v in $VARS ; do
  TABLE=`ls ${v}*.????_c??????.nc | cut -d"_" -f2 | cut -d"." -f1 | sort | uniq`
  for t in $TABLE ; do
    EXPIDS=`ls ${v}_${t}.*.????_c??????.nc | cut -d"." -f2 | sort | uniq`
    for e in $EXPIDS ; do
      MODEL=`ls ${v}_${t}.${e}.*.????_c??????.nc | cut -d"." -f3 | sort | uniq`
      for m in $MODEL ; do
        COMP=`ls ${v}_${t}.${e}.${m}.*.????_c??????.nc | cut -d"." -f4 | sort | uniq`
        for c in $COMP ; do
          DECADE=`ls ${v}_${t}.${e}.${m}.${c}.????_c??????.nc | cut -d"." -f5 | cut -c1-3 | sort | uniq`
          for d in $DECADE ; do
            NF=`ls ${v}_${t}.${e}.${m}.${c}.${d}?_c??????.nc | wc -l`
            if [ $NF -eq 10 ] ; then
              Y1=`ls ${v}_${t}.${e}.${m}.${c}.${d}?_c??????.nc | cut -d"." -f5 | cut -c1-4 | head -1`
              Y2=`ls ${v}_${t}.${e}.${m}.${c}.${d}?_c??????.nc | cut -d"." -f5 | cut -c1-4 | tail -1`
              TS=`date '+%y%m%d'`
              if [ "$t" == "A2" ] ; then
                 DF=${v}_${t}.${e}.${m}.${c}.${Y1}-01-01_cat_${Y2}-12-31_c${TS}.nc
              else
                 DF=${v}_${t}.${e}.${m}.${c}.${Y1}-01_cat_${Y2}-12_c${TS}.nc
              fi
              $NCRCAT -O ${v}_${t}.${e}.${m}.${c}.${d}[0-9]_*.nc $DF
              if [ $? -eq 0 ] ; then
                rm -f ${v}_${t}.${e}.${m}.${c}.${d}[0-9]_*.nc
              fi
            fi
          done
        done
      done
    done
  done
done
