#!/bin/sh
#
# Concatenate months of IPCC netCDF files into years
#
if [ $# -ne 0 ] ; then
   echo "Usage: cf_var_mon_to_year"
   exit 1
fi
# 
# Check for ncrcat
#
if [ ! $NCRCAT ] ; then
  TEST4NCRCAT=`which ncrcat 2>&1`
  if [ $? -eq 0 ] ; then
    NCRCAT=`which ncrcat`
  else
    echo "NCRCAT not in PATH - UNDEFINED"
    exit 1
  fi
fi
#
VARS=`ls | egrep '\-..\.nc$' | cut -d"_" -f1 | uniq`
if [ $? -eq 0 ] ; then
   TABLE=`ls | egrep '\-..\.nc$' | cut -d"_" -f2 | cut -d"." -f1 | sort | uniq`
  EXPIDS=`ls | egrep '\-..\.nc$' | cut -d"." -f2 | sort | uniq`
   MODEL=`ls | egrep '\-..\.nc$' | cut -d"." -f3 | sort | uniq`
    COMP=`ls | egrep '\-..\.nc$' | cut -d"." -f4 | sort | uniq`
   YEARS=`ls | egrep '\-..\.nc$' | cut -d"." -f5 | cut -c1-4 | sort | uniq`
#
  for v in $VARS ; do
    for t in $TABLE ; do
      for e in $EXPIDS ; do
        for y in $YEARS ; do
          for m in $MODEL ; do
            for c in $COMP ; do
              NUM=`ls ${v}_${t}.${e}.${m}.${c}.${y}-??.nc | wc -l`
              if [ $NUM -eq 12 ] ; then
                DF=${v}_${t}.${e}.${m}.${c}.${y}.nc
                $NCRCAT -h -O ${v}_${t}.${e}.${m}.${c}.${y}-??.nc $DF
                if [ $? -eq 0 ] ; then
                  rm -f ${v}_${t}.${e}.${m}.${c}.${y}-??.nc
                fi
              fi
            done
          done
        done
      done
    done
  done
fi
