#!/bin/sh
#
# Concatenate years of IPCC netCDF files into bigger chunks
#
if [ $# -ne 0 ] ; then
   echo "Usage: cf_var_year_to_all"
   exit 1
fi
# 
# Check for ncrcat
#
if [ `echo $NCRCAT | wc -c` -eq 0 ] ; then
  TEST4NCRCAT=`which ncrcat 2>&1`
  if [ $? -eq 0 ] ; then
    NCRCAT=`which ncrcat`
  else
    echo "NCRCAT not in PATH - UNDEFINED"
    exit 1
  fi
else
  echo "NCRCAT undefined"
  exit 1
fi
#
 TABLE=`ls | egrep '_[0-9][0-9][0-9][0-9]\.nc$' | cut -d"_" -f2 | sort | uniq`
 MODEL=`ls | egrep '_[0-9][0-9][0-9][0-9]\.nc$' | cut -d"_" -f3 | sort | uniq`
EXPIDS=`ls | egrep '_[0-9][0-9][0-9][0-9]\.nc$' | cut -d"_" -f4 | sort | uniq`
REALZN=`ls | egrep '_[0-9][0-9][0-9][0-9]\.nc$' | cut -d"_" -f5 | sort | uniq`
#
for m in $MODEL ; do
  for r in $REALZN ; do
    for t in $TABLE ; do
      VARS=`ls | egrep "_${t}_" | egrep "_${m}_" | egrep "_${r}_" | egrep '_[0-9][0-9][0-9][0-9]\.nc$' | cut -d"_" -f1 | uniq`
      for v in $VARS ; do
        for e in $EXPIDS ; do
          if [ $YRCOUNT ] ; then
            NUM=`ls | egrep "^${v}_${t}_${m}_${e}_${r}_" | egrep '_[0-9][0-9][0-9][0-9]\.nc$' | wc -l`
            if [ $NUM = $YRCOUNT ] ; then
#              TS=`date '+%y%m%d'`
              Y1=`ls ${v}_${t}_${m}_${e}_${r}_????.nc | head -1 | cut -d"_" -f6 | cut -c1-4`
              Y2=`ls ${v}_${t}_${m}_${e}_${r}_????.nc | tail -1 | cut -d"_" -f6 | cut -c1-4`
              DF=${v}_${t}_${m}_${e}_${r}_${Y1}01-${Y2}12.nc
              $NCRCAT -O ${v}_${t}_${m}_${e}_${r}_????.nc $DF
              if [ $? -eq 0 ] ; then
                rm -f ${v}_${t}_${m}_${e}_${r}_????.nc
                echo "Concatenated "$DF" and checked year count: "$YRCOUNT
              else
                echo "Failure on concat of "${r}"_"${p}"_"${v}" files"
                exit 1
              fi
            else
              echo "Missing year(s) from "${v}"_"${t}"_"${e}" files"
              echo "Count is "$NUM" should be "$YRCOUNT
              exit 1
            fi
          else
            TS=`date '+%y%m%d'`
            Y1=`ls ${v}_${t}_${m}_${e}_${r}_????.nc | head -1 | cut -d"_" -f6 | cut -c1-4`
            Y2=`ls ${v}_${t}_${m}_${e}_${r}_????.nc | tail -1 | cut -d"_" -f6 | cut -c1-4`
            case "$t" in
              Amon | Lmon | Omon | LImon | OImon | Oclim | Oyr | aero | cfMon | cfOff )
                DF=${v}_${t}_${m}_${e}_${r}_${Y1}01-${Y2}12_v${TS}.nc ;;
              da | 6hrPlev | 6hrLev | 3hr | cfDa | cf3hr | cf30min )
                DF=${v}_${t}_${m}_${e}_${r}_${Y1}0101-_${Y2}1231_v${TS}.nc ;;
              * )
                echo "Unable to concatenate because "$t" is unknown TABLE"
                exit 1 ;;
            esac
            $NCRCAT -O ${v}_${t}_${m}_${e}_${r}_????.nc $DF
            if [ $? -eq 0 ] ; then
              rm -f ${v}_${t}_${m}_${e}_${r}_????.nc
              echo "Concatenated "$DF" WITHOUT checking year count"
            else
              echo "Failure on concat of "${r}"_"${p}"_"${v}" files"
              exit 1
            fi
          fi
        done
      done
    done
  done
done
