#!/bin/sh
#
# Concatenate months of IPCC netCDF files into years
#
if [ $# -ne 0 ] ; then
   echo "Usage: cf_var_mon_to_year"
   exit 1
fi
# 
# Check for ncrcat
#
if [ ! $NCRCAT ] ; then
  TEST4NCRCAT=`which ncrcat 2>&1`
  if [ $? -eq 0 ] ; then
    NCRCAT=`which ncrcat`
  else
    echo "NCRCAT not in PATH - UNDEFINED"
    exit 1
  fi
else
  echo "NCRCAT undefined"
  exit 1
fi
#
VARS=`ls | egrep '_......\.nc$' | cut -d"_" -f1 | uniq`
if [ $? -eq 0 ] ; then
   TABLE=`ls | egrep '_......\.nc$' | cut -d"_" -f2 | sort | uniq`
   MODEL=`ls | egrep '_......\.nc$' | cut -d"_" -f3 | sort | uniq`
  EXPIDS=`ls | egrep '_......\.nc$' | cut -d"_" -f4 | sort | uniq`
  REALZN=`ls | egrep '_......\.nc$' | cut -d"_" -f5 | sort | uniq`
   YEARS=`ls | egrep '_......\.nc$' | cut -d"_" -f6 | cut -c1-4 | sort | uniq`
#
  for v in $VARS ; do
    for t in $TABLE ; do
      for m in $MODEL ; do
        for e in $EXPIDS ; do
          for r in $REALZN ; do
            for y in $YEARS ; do
              NUM=`ls ${v}_${t}_${m}_${e}_${r}_${y}[0-1][0-9].nc | wc -l`
              if [ $NUM -eq 12 ] ; then
                DF=${v}_${t}_${m}_${e}_${r}_${y}.nc
                $NCRCAT -h -O ${v}_${t}_${m}_${e}_${r}_${y}[0-1][0-9].nc $DF
                if [ $? -eq 0 ] ; then
                  rm -f ${v}_${t}_${m}_${e}_${r}_${y}[0-1][0-9].nc
                fi
              fi
            done
          done
        done
      done
    done
  done
fi
