#!/bin/sh
#
# Compress data with level 1 non-lossy compression
#
if [ $# -ne 0 ] ; then
  echo "Usage: compress_data"
  ./update_status error compress_data
  exit 1
fi
#
# Check for ncks
#
if [ ! $NCKS ] ; then
  TEST4NCKS=`which ncrcat 2>&1`
  if [ $? -eq 0 ] ; then
    NCKS=`which ncks`
  else
    echo "NCKS not in PATH - UNDEFINED"
    ./update_status error compress_data
    exit 1
  fi
fi
#
cd $CACHEDIR
#
if [ `ls CAT.*.nc | wc -l` -ne 0 ] ; then
  for CATFILE in `ls CAT.*.nc` ; do
    NC4Z_FILE=`echo $CATFILE | sed -e 's/^CAT\.//g'`
    $NCKS -4 -L 1 $CATFILE $NC4Z_FILE
    if [ $? = 0 ] ; then
      rm -f $CATFILE
    else
      echo "Error on compression of "${CATFILE}". Exit."
      ../update_status error compress_data
      exit 1
    fi
  done
fi
#
cd $LOCAL_PROC
