#!/bin/sh
#
# Concatenate data as needed by argument
#
if [ $# -eq 0 ] ; then
  echo "Usage: concatenate_data [Y|D|5|A] (required)"
  echo " Y: concatenate years     (from months)"
  echo " D: concatenate decades   (from years)"
  echo " 5: concatenate 5-years   (from years)"
  echo " A: concatenate all years (from years)"
  exit 1
fi
if [ $# -eq 1 ] ; then
  TCAT=$1
  if [ "$TCAT" != "Y" ] ; then
    if [ "$TCAT" != "D" ] ; then
      if [ "$TCAT" != "5" ] ; then
        if [ "$TCAT" != "A" ] ; then
          echo $TCAT" not defined argument"
          echo "Usage: concatenate_data [Y|D|5|A] (required)"
          echo " Y: concatenate years     (from months)"
          echo " D: concatenate decades   (from years)"
          echo " 5: concatenate 5-years   (from years)"
          echo " A: concatenate all years (from years)"
          exit 1
        fi
      fi
    fi
  fi
fi
#
cd $PROCDIR
#
if [ $DO_PROC -ne 0 ] ; then
  cd ${PROCDIR}
  if [ "$TCAT" = "Y" ] ; then
    for e in `ls -d *d.d` ; do
      cd ${PROCDIR}/${e}
      ../var_mon_to_year
      if [ $? -ne 0 ] ; then
        echo "Error from var_mon_to_year"
        exit 1
      fi
    done
  fi
  if [ "$TCAT" = "D" ] ; then
    for e in `ls -d *4d.d` ; do
      cd ${PROCDIR}/${e}
      ../var_year_to_dec
      if [ $? -ne 0 ] ; then
        echo "Error from var_year_to_dec"
        echo $CASE" "${HIST}" "${e}
        exit 1
      else
        if [ `ls CAT.${CASE}.${HIST}.*nc | wc -l` -ne 0 ] ; then
          mv CAT.${CASE}.${HIST}.*.nc $CACHEDIR
        fi
      fi
    done
  fi
  if [ "$TCAT" = "5" ] ; then
    for e in `ls -d *d.d` ; do
      cd ${PROCDIR}/${e}
      ../var_year_to_5yr
      if [ $? -ne 0 ] ; then
        echo "Error from var_year_to_dec"
        echo $CASE" "${HIST}" "${e}
        exit 1
      else
        if [ `ls CAT.${CASE}.${HIST}.*nc | wc -l` -ne 0 ] ; then
          mv CAT.${CASE}.${HIST}.*.nc $CACHEDIR
        fi
      fi
    done
  fi
  if [ "$TCAT" = "A" ] ; then
    for e in `ls -d *d.d` ; do
      cd ${PROCDIR}/${e}
      ../var_year_to_all
      if [ $? -ne 0 ] ; then
        echo "Error from var_year_to_all"
        echo $CASE" "${HIST}" "${e}
        exit 1
      else
        if [ `ls CAT.${CASE}.${HIST}.*nc | wc -l` -ne 0 ] ; then
          mv CAT.${CASE}.${HIST}.*.nc $CACHEDIR
        fi
      fi
    done
  fi
  cd ${PROCDIR}
fi
#
if [ $DO_CMIP -ne 0 ] ; then
  cd ${PROCDIR}/CMIP
  ./${CMIP}_var_mon_to_year
  if [ $? -ne 0 ] ; then
    echo "Error from "${CMIP}"_var_mon_to_year"
    exit 1
  fi
fi
