#!/bin/sh
#
# Concatenate months -> years
#
if [ $# -ne 0 ] ; then
  echo "Usage: concatenate_year"
  exit 1
fi
#
cd $PROCDIR
#
if [ $DO_PROC -ne 0 ] ; then
  cd ${PROCDIR}
  for e in `ls -d *d.d` ; do
    cd ${PROCDIR}/${e}
    ../var_mon_to_year
    if [ $? -ne 0 ] ; then
      echo "Error from var_mon_to_year"
      exit 1
    fi
    cd ${PROCDIR}
  done
  cd ${PROCDIR}
fi
#
if [ $DO_CMIP -ne 0 ] ; then
  cd ${PROCDIR}/CMIP
  ./${CMIP}_var_mon_to_year
  if [ $? -ne 0 ] ; then
    echo "Error from "${CMIP}"_var_mon_to_year"
    exit 1
  fi
fi
