#!/bin/sh
#
# Concatenate data as needed by argument
#
if [ $# -eq 0 ] ; then
  echo "Usage: concatenate_data [M2Y|Y2D|Y2A|D2C] (required)"
  echo " M2Y: concatenate months to years"
  echo " Y2D: concatenate years to decades"
  echo " Y2A: concatenate years to all years"
  echo " D2C: concatenate decades to centuries"
  ./procstat.sh error concatenate_data
  exit 1
fi
if [ $# -eq 1 ] ; then
  TCAT=$1
  if [ "$TCAT" != "M2Y" ] ; then
    if [ "$TCAT" != "Y2D" ] ; then
      if [ "$TCAT" != "Y2A" ] ; then
        if [ "$TCAT" != "D2C" ] ; then
          echo "Usage: concatenate_data [M2Y|Y2D|Y2A|D2C] (required)"
          echo " M2Y: concatenate months to years"
          echo " Y2D: concatenate years to decades"
          echo " Y2A: concatenate years to all years"
          echo " D2C: concatenate decades to centuries"
        fi
      fi
    fi
  fi
fi
#
cd $LOCAL_PROC
#
if [ $DO_PROC ] ; then
  if [ $DO_PROC -ne 0 ] ; then
    cd ${LOCAL_PROC}
    if [ "$TCAT" = "M2Y" ] ; then
      for e in `ls -d *d.d` ; do
        cd ${LOCAL_PROC}/${e}
        ../var_mon_to_year
        if [ $? -ne 0 ] ; then
          echo "Error from var_mon_to_year"
	  ./procstat.sh error concatenate_data
          exit 1
        fi
      done
    fi
    if [ "$TCAT" = "Y2D" ] ; then
      for e in `ls -d *4d.d` ; do
        cd ${LOCAL_PROC}/${e}
        ../var_year_to_dec
        if [ $? -ne 0 ] ; then
          echo "Error from var_year_to_dec"
          echo $CASE" "${HIST}" "${e}
	  ./procstat.sh error concatenate_data
          exit 1
        else
          if [ `ls | egrep "^CAT.${CASE}.${HIST}" | egrep '\.nc$' | wc -l` -ne 0 ] ; then
            mv CAT.${CASE}.${HIST}.*.nc $CACHEDIR
          fi
        fi
      done
    fi
    if [ "$TCAT" = "Y2A" ] ; then
      for e in `ls -d *d.d` ; do
        cd ${LOCAL_PROC}/${e}
        ../var_year_to_all
        if [ $? -ne 0 ] ; then
          echo "Error from var_year_to_all"
          echo $CASE" "${HIST}" "${e}
	  ./procstat.sh error concatenate_data
          exit 1
        else
          if [ `ls | egrep "^CAT.${CASE}.${HIST}" | egrep '\.nc$' | wc -l` -ne 0 ] ; then
            mv CAT.${CASE}.${HIST}.*.nc $CACHEDIR
          fi
        fi
      done
    fi
    if [ "$TCAT" = "D2C" ] ; then
      for e in `ls -d *d.d` ; do
        cd ${LOCAL_PROC}/${e}
        ../var_dec_to_cen
        if [ $? -ne 0 ] ; then
          echo "Error from var_dec_to_cen"
          echo $CASE" "${HIST}" "${e}
	  ./procstat.sh error concatenate_data
          exit 1
        else
          if [ `ls | egrep "^CAT.${CASE}.${HIST}" | egrep '\.nc$' | wc -l` -ne 0 ] ; then
            mv CAT.${CASE}.${HIST}.*.nc $CACHEDIR
          fi
        fi
      done
    fi
    cd ${LOCAL_PROC}
  fi
fi
#
if [ $DO_CMIP ] ; then
  if [ $DO_CMIP -ne 0 ] ; then
    cd ${LOCAL_PROC}/CMIP
    if [ "$TCAT" = "M2Y" ] ; then
      ./${CMIP}_var_mon_to_year
      if [ $? -ne 0 ] ; then
        echo "Error from "${CMIP}"_var_mon_to_year"
	./procstat.sh error concatenate_data
        exit 1
      fi
    fi
    if [ "$TCAT" = "Y2A" ] ; then
      ./${CMIP}_var_year_to_all
      if [ $? -ne 0 ] ; then
        echo "Error from "${CMIP}"_var_mon_to_year"
	./procstat.sh error concatenate_data
        exit 1
      fi
    fi
  fi
fi
