#!/bin/sh
#
# Concatenate LME pop.h/pop.h.nday1 data as needed
#
if [ $# -ne 0 ] ; then
  echo "Usage: concatenate_lme_data"
  ./update_status error concatenate_lme_data
  exit 1
fi
#
# Check for CACHEDIR
#
if [ ! $CACHEDIR ] ; then
  echo "No CACHEDIR defined. CAT files stay in subdirs"
fi
#
# Check for ncks
#
if [ ! $NCKS ] ; then
  TEST4NCKS=`which ncrcat 2>&1`
  if [ $? -eq 0 ] ; then
    NCKS=`which ncks`
  else
    echo "NCKS not in PATH - UNDEFINED"
    ./update_status error concatenate_data
    exit 1
  fi
fi
#
cd $LOCAL_PROC
#
# Process time-variant fields 
#
if [ `/bin/ls -d *.d | wc -l` -ne 0 ] ; then
  for IDIR in `/bin/ls -d *.d` ; do
    cd ${LOCAL_PROC}/${IDIR}
    ../var_lme_year_to_cen
    if [ $? = 0 ] ; then
      if [ `/bin/ls | egrep "^CAT\." | egrep '\.nc$' | wc -l` -ne 0 ] ; then
        for CATFILE in `/bin/ls | egrep "^CAT\." | egrep '\.nc$'` ; do
          mv $CATFILE $CACHEDIR
        done
      fi
    else
      echo "Error from var_lme_year_to_cen"
      ./update_status error concatenate_data
      exit 1
    fi
  done
fi
#
cd ${LOCAL_PROC}
