#!/bin/sh -xv
#
if [ $# = 1 ] ; then
  NCL_FILE=$1
else
  echo "Usage: create_ipcc_data file"
  exit 1
fi
#
if [ ! -f $NCL_FILE ] ; then
  echo $NCL_FILE "not found. Exit."
  exit 1
fi
# 
# Check for NCL
#
if [ ! $NCL ] ; then
  TEST4NCL=`which ncl 2<&1 >& /dev/null`
  if [ $? -eq 0 ] ; then
    NCL=`which ncl`
  else
    echo "NCL not in PATH - UNDEFINED"
    exit 1
  fi
fi
#
# Check for NCARG_ROOT
#
if [ ! $NCARG_ROOT ] ; then
  if [ "$LOCATION" = "OR" ] ; then
    NCARG_ROOT=/sw/analysis-x64/ncl/5.0.0/sl5.0_binary
    export NCARG_ROOT
  fi
  if [ "$LOCATION" = "NE" ] ; then
    NCARG_ROOT=/usr/common/usg/ncar/5.0.0
    export NCARG_ROOT
  fi
else
  echo "NCARG_ROOT UNDEFINED"
  exit 1
fi
#
export NCL_FILE
#
CHEK=`ls $NCL_FILE | cut -d"." -f3 | cut -c1-2 | uniq`
if [ $CHEK == "ES" ] ; then
  F_TVAL=6
else
  F_TVAL=5
fi
#
NCL_TVAL=`echo $NCL_FILE | cut -d"." -f${F_TVAL}`
NCL_SCRIPT=CCSM_${TYPE}_${CMIP}.ncl ; export NCL_SCRIPT
#
if [ ! -d ./IPCC ] ; then
   mkdir ./IPCC
fi
#
if [ "$TYPE" = "icem" ] || [ "$TYPE" = "ocnm" ] ; then # We are processing regridded ocean/ice data
  F_TVAL=`expr $F_TVAL + 1`
  NCL_TVAL=`echo $NCL_FILE | cut -d"." -f${F_TVAL}`
  if [ "$TYPE" = "ocnm" ] ; then
    if [ "$NCL_TVAL" = "nc" ] ; then # We are processing an original ocean file for transports
      F_TVAL=`expr $F_TVAL - 1`
      NCL_TVAL=`echo $NCL_FILE | cut -d"." -f${F_TVAL}`
      NCL_SCRIPT=CCSM_trans_${CMIP}.ncl ; export NCL_SCRIPT
    fi
  fi
fi
#
export NCL_TVAL
NCL_VERSION=`$NCL -V` ; export NCL_VERSION
$NCL < $NCL_SCRIPT 2<&1 >& /dev/null
if [ $? -ne 0 ] ; then
   echo "NCL ERROR on "$NCL_FILE
   exit 1
fi
