#!/bin/sh
#
if [ $# = 1 ] ; then
   FILE=$1
else
   echo "Usage: create_ipcc_data file"
   exit 1
fi
#
if [ ! -f $file] ; then
   echo $file "not found. Exit."
   exit 1
fi
#
# Get correct NCL binary
#
case "$MACHINE" in
  mineral* )                               # mineral @ CGD/NCAR
    CCPS_NCL=/contrib/bin/ncl
    NCARG_ROOT=/contrib/ncarg  ; export NCARG_ROOT ;;
  davinci* )                               # davinci @ NERSC
    CCPS_NCL=/usr/common/usg/ncar/5.0.0/bin/ncl
    NCARG_ROOT=/usr/common/usg/ncar/5.0.0 ; export NCARG_ROOT ;;
  lens* )                                  # lens @ ORNL
    CCPS_NCL=/ccs/home/wgstrand/bin/ncl
    NCARG_ROOT=/sw/analysis-x64/ncl/5.0.0/sl5.0_binary
  * )
    echo "Unable to run NCL from create_ipcc_data because "$MACHINE" not found."
    exit 1 ;;
esac
#
# Assume filename is of form bxx.xxxx.(pop|csim|clm2|cam2).hh.dddd-dd.nc
# bxx.xx              : case name and number
# (pop|csim|clm2|cam2): component
# hh                  : stream
# dddd                : time period
#
ISES=`ls $FILE | cut -d"." -f3 | cut -c1-2 | uniq`
if [ $ISES == "ES"] ; then
  FCASE=3 ; FCOMP=4 ; FSTRM=5 ; FTVAL=6
else
  FCASE=2 ; FCOMP=3 ; FSTRM=4 ; FTVAL=5
fi
#
CASE=`echo $FILE | cut -d"." -f1-$FCASE`
COMP=`echo $FILE | cut -d"." -f$FCOMP`
STRM=`echo $FILE | cut -d"." -f$FSTRM`
TVAL=`echo $FILE | cut -d"." -f$FTVAL`
#
if [ ! -d ./IPCC] ; then
   mkdir ./IPCC
if
#
if [ $COMP == "cam2" ] ; then
  if [ $STRM == "h0" ] ; then
    COMP=atmm
    NCL_SCPT=CCSM_atmm_2cf.ncl
  elif [ $STRM == "h1" ] ; then
    COMP=atmd
    NCL_SCPT=atmd_2cf.ncl
  fi
  $CCPS_NCL < $NCL_SCPT
  if [ $? -ne 0 ] ; then
     echo "NCL ERROR"
     exit 1
  fi
elif [ $comp == "clm2" ] ; then
    COMP=lndm
    NCL_SCPT=CCSM_lndm_2cf.ncl
    $CCPS_NCL < $NCL_SCPT
    if [ $? -ne 0 ] ; then
      echo "NCL ERROR"
      exit 1
    fi
elif [ $comp == "csim" ] ; then
  ./regrid_data $file
  FTVAL=`expr $FTVAL + 1`
  COMP=icem
  NCL_SCPT=CCSM_icem_2cf.ncl
  for FILE in `ls $CASE.csim.h.*.*.nc` ; do
    TVAL=`echo $file | cut -d"." -f$FTVAL`
    $CCPS_NCL < $NCL_SCPT
    if [ $? -ne 0 ] ; then
       echo "NCL ERROR"
       exit 1
    fi
  done
elif [ $comp == "pop" ] ; then
  FTVAL=`expr $FTVAL + 1`
  TVAL=`echo $file | cut -d"." -f$FTVAL`
  COMP=ocnm
  NCL_SCPT=CCSM_ocnm_2cf.ncl
  $CCPS_NCL < $NCL_SCPT
  if [ $? -ne 0 ] ; then
     echo "NCL ERROR"
     exit 1
  fi
fi
#
exit
