#!/bin/sh
# 
# Check for ncl
#
if [ ! $NCRCAT ] ; then
  TEST4NCRCAT=`which ncrcat 2>&1`
  if [ $? -eq 0 ] ; then
    NCRCAT=`which ncrcat`
  else
    echo "NCRCAT not in PATH - UNDEFINED"
    exit 1
  fi
fi
# 
# Check for TPER
#
if [ ! $TPER ] ; then
  echo "TPER undefined. Assume daily"
  TPER="day" ; export TPER
fi
# 
# Check for HIST
#
if [ ! $HIST ] ; then
  echo "HIST undefined. Assume cam2.h1"
  HIST="cam2.h1" ; export HIST
fi
#
# Parse first filename
#
FILE=`ls | egrep "*.${HIST}.*" | egrep '\-[0-9][0-9][0-9][0-9][0-9]\.nc$' | head -n 1`
FLEN=`echo $FILE | wc -c`
NDOT=0
CSTR=1
while [ $CSTR -le $FLEN ] ; do
  CURC=`echo $FILE | cut -c${CSTR}-${CSTR}`
  if [ "$CURC" = "." ] ; then
     NDOT=`expr '(' $NDOT ')' '+' '1'`
  fi
  CSTR=`expr '(' $CSTR ')' '+' '1'`
done
IDOT=1
DPFX=1
while [ $IDOT -le $NDOT ] ; do
  CURC=`echo $FILE | cut -d "." -f${IDOT}-${IDOT}`
  case "$CURC" in
    cam2 )
      DPFX=`expr '(' $IDOT ')' '+' '1'` ;;
    clm2 )
      DPFX=`expr '(' $IDOT ')' '+' '1'` ;;
    pop )
      DPFX=`expr '(' $IDOT ')' '+' '1'` ;;
    csim )
      DPFX=`expr '(' $IDOT ')' '+' '1'` ;;
  esac
  IDOT=`expr '(' $IDOT ')' '+' '1'`
done
OUTPFX=`echo $FILE | cut -d"." -f1-${DPFX}`
FT=`expr '(' $DPFX ')' '+' '1'`
#
YEARS=`ls ${OUTPFX}.????????-?????.nc | cut -d"." -f${FT} | cut -c1-4 | sort | uniq`
for y in $YEARS ; do
  MON=`ls ${OUTPFX}.${y}????-?????.nc | cut -d"." -f${FT} | cut -c5-6 | uniq`
  for m in $MON ; do
  # Jan, Mar, May, Jul, Aug, Oct, Dec
    if [ "$m" = "01" ] || [ "$m" = "03" ] || [ "$m" = "05" ] || [ "$m" = "07" ] || [ "$m" = "08" ] || [ "$m" = "10" ] || [ "$m" = "12" ] ; then
      case "$TPER" in
        day )
          NDAY=31  ;;
        hr6 )
          NDAY=124 ;;
        hr3 )
          NDAY=248 ;;
      esac
    fi
  # Apr, Jun, Sep, Nov
    if [ "$m" = "04" ] || [ "$m" = "06" ] || [ "$m" = "09" ] || [ "$m" = "11" ] ; then
      case "$TPER" in
        day )
          NDAY=30  ;;
        hr6 )
          NDAY=120 ;;
        hr3 )
          NDAY=240 ;;
      esac
    fi
  # Feb
    if [ "$m" = "02" ] ; then
      case "$TPER" in
        day )
          NDAY=28  ;;
        hr6 )
          NDAY=112 ;;
        hr3 )
          NDAY=224 ;;
      esac
    fi
    MDAY=`ls ${OUTPFX}.${y}${m}??-?????.nc | wc -l`
    if [ $MDAY -eq $NDAY ] ; then
      MONFIL=${OUTPFX}.${y}-${m}.nc
      $NCRCAT -O ${OUTPFX}.${y}${m}??-?????.nc $MONFIL
      if [ $? -eq 0 ] ; then
        if [ $# -eq 1 ] ; then
           rm -f ${OUTPFX}.${y}${m}??-?????.nc
        fi
        echo "Created "$MONFIL
      fi
    fi
  done
done
