#!/bin/sh
#
# Concatenate months of netCDF history files into years
#
if [ $# -ne 0 ] ; then
  echo "Usage: hist_mon_to_year"
  ./procstat.sh error hist_mon_to_year
  exit 1
fi
# 
# Check for ncrcat
#
if [ ! $NCRCAT ] ; then
  TEST4NCRCAT=`which ncrcat 2>&1`
  if [ $? -eq 0 ] ; then
    NCRCAT=`which ncrcat`
  else
    echo "NCRCAT not in PATH - UNDEFINED"
    ./procstat.sh error hist_mon_to_year
    exit 1
  fi
fi
#
# Parse first filename
#
FILE=`ls | egrep '\.nc$' | head -n 1`
FLEN=`echo $FILE | wc -c`
NDOT=0
CSTR=1
while [ $CSTR -le $FLEN ] ; do
  CURC=`echo $FILE | cut -c${CSTR}-${CSTR}`
  if [ "$CURC" = "." ] ; then
     NDOT=`expr '(' $NDOT ')' '+' '1'`
  fi
  CSTR=`expr '(' $CSTR ')' '+' '1'`
done
IDOT=1
DCAS=1
DTIM=1
DHT1=1
DHT2=1
while [ $IDOT -le $NDOT ] ; do
  CURC=`echo $FILE | cut -d "." -f${IDOT}-${IDOT}`
  case "$CURC" in
    cam2 | cam | clm2 | pop | csim | cice )
      DCAS=`expr '(' $IDOT ')' '-' '1'`
      DHT1=$IDOT ;;
  esac
  DTIM=$IDOT
  IDOT=`expr '(' $IDOT ')' '+' '1'`
done
DHT2=`expr '(' $DHT1 ')' '+' '1'`
#
CASES=`ls | egrep '\.([0-9][0-9][0-9][0-9]|[0-9][0-9][0-9][0-9][0-9])\-..\.nc$' | cut -d"." -f1-${DCAS} | sort | uniq`
 HIST=`ls | egrep '\.([0-9][0-9][0-9][0-9]|[0-9][0-9][0-9][0-9][0-9])\-..\.nc$' | cut -d"." -f${DHT1},${DHT2} | sort | uniq`
#
# Check for pop.h.nday1
#
if [ "$HIST" = "pop.h" ] ; then
  DYCK=`expr '(' $DHT2 ')' '+' '1'`
  ODAY=`ls | egrep '\.([0-9][0-9][0-9][0-9]|[0-9][0-9][0-9][0-9][0-9])\-..\.nc$' | cut -d"." -f${DYCK} | sort | uniq`
  if [ "$ODAY" = "nday1" ] || [ "$ODAY" = "h2" ] ; then
    DHT2=$DYCK
    DTIM=`expr '(' $DTIM ')' '+' '1'`
    HIST=`ls | egrep '\.([0-9][0-9][0-9][0-9]|[0-9][0-9][0-9][0-9][0-9])\-..\.nc$' | cut -d"." -f${DHT1}-${DHT2} | sort | uniq`
  fi
fi
#
for c in $CASES ; do      
  for h in $HIST ; do
    YEARS4=`ls | egrep "${c}\.${h}\.[0-9][0-9][0-9][0-9]\-..\.nc"      | cut -d"." -f${DTIM} | cut -c1-4 | sort | uniq`
    YEARS5=`ls | egrep "${c}\.${h}\.[0-9][0-9][0-9][0-9][0-9]\-..\.nc" | cut -d"." -f${DTIM} | cut -c1-5 | sort | uniq`
    YEARS=${YEARS4}" "${YEARS5}
    for y in $YEARS ; do
      NUM=`ls ${c}\.${h}\.${y}-??\.nc | wc -l`
      if [ $NUM -eq 12 ] ; then
        DF=${c}.${h}.${y}.nc
        if [ $DF ] ; then
          $NCRCAT -O ${c}.${h}.${y}-??.nc $DF
          if [ $? -eq 0 ] ; then
            echo "Created: "$DF
            rm -f ${c}.${h}.${y}-??.nc
          fi
        else
          echo "Undefined DF: "$DF
          ./procstat.sh error hist_mon_to_year
          exit 1
        fi
      fi
    done
  done
done
