#!/bin/sh
#
# Concatenate years of by-field CCSM netCDF from LME into 100-year-long segments
#
if [ $# -ne 0 ] ; then
  echo "Usage: lme_year_to_cen"
  ./update_status error lme_year_to_cen
  exit 1
fi
# 
# Check for ncrcat
#
if [ ! $NCRCAT ] ; then
  TEST4NCRCAT=`which ncrcat 2>&1`
  if [ $? -eq 0 ] ; then
    NCRCAT=`which ncrcat`
  else
    echo "NCRCAT not in PATH - UNDEFINED"
    ./update_status error lme_year_to_cen
    exit 1
  fi
fi
# 
# Check for ncrcat
#
if [ ! $TPER ] ; then
  echo "TPER undefined. Assume monthly"
  TPER="mon" ; export TPER
fi
#
# Parse first filename
#
FILE=`ls | egrep '\.[0-9][0-9][0-9][0-9]\.nc$' | head -n 1`
FLEN=`echo $FILE | wc -c`
NDOT=0
CSTR=1
while [ $CSTR -le $FLEN ] ; do
  CURC=`echo $FILE | cut -c${CSTR}-${CSTR}`
  if [ "$CURC" = "." ] ; then
     NDOT=`expr '(' $NDOT ')' '+' '1'`
  fi
  CSTR=`expr '(' $CSTR ')' '+' '1'`
done
IDOT=1
DCAS=1
DVAR=1
DHT1=1
DHT2=1
while [ $IDOT -le $NDOT ] ; do
  CURC=`echo $FILE | cut -d "." -f${IDOT}-${IDOT}`
  case "$CURC" in
    cam2 | cam | clm2 | pop | csim | cice | rtm )
      DCAS=`expr '(' $IDOT ')' '-' '1'`
      DVAR=`expr '(' $IDOT ')' '+' '1'`
      DHT1=$IDOT ;;
  esac
  IDOT=`expr '(' $IDOT ')' '+' '1'`
done
#
DCMP=$DHT1
COMP=`echo $FILE | cut -d"." -f${DCMP}`
#
DHT2=`expr '(' $DHT1 ')' '+' '1'`
DVAR=`expr '(' $DVAR ')' '+' '1'`
DTIM=`expr '(' $DVAR ')' '+' '1'`
#
CASES=`ls | egrep '\.[0-9][0-9][0-9][0-9]\.nc$' | cut -d"." -f1-${DCAS} | sort | uniq`
 VARS=`ls | egrep '\.[0-9][0-9][0-9][0-9]\.nc$' | cut -d"." -f${DVAR} | sort | uniq`
 HIST=`ls | egrep '\.[0-9][0-9][0-9][0-9]\.nc$' | cut -d"." -f${DHT1}-${DHT2} | sort | uniq`
 COMP=`ls | egrep '\.[0-9][0-9][0-9][0-9]\.nc$' | cut -d"." -f${DCMP} | sort | uniq`
#
# Check for pop.h.nday1/h2/ecosys
#
if [ "$HIST" = "pop.h" ] ; then
  DYCK=`expr '(' $DHT2 ')' '+' '1'`
  ODAY=`ls | egrep '\.[0-9][0-9][0-9][0-9]\.nc$' | cut -d"." -f${DYCK} | sort | uniq`
  if [ "$ODAY" = "nday1" ] || [ "$ODAY" = "h2" ] ; then
    DHT2=$DYCK
    DVAR=`expr '(' $DVAR ')' '+' '1'`
    DTIM=`expr '(' $DVAR ')' '+' '1'`
    VARS=`ls | egrep '\.[0-9][0-9][0-9][0-9]\.nc$' | cut -d"." -f${DVAR} | sort | uniq`
    HIST=`ls | egrep '\.[0-9][0-9][0-9][0-9]\.nc$' | cut -d"." -f${DHT1}-${DHT2} | sort | uniq`
  fi
fi
#
for c in $CASES ; do
  for h in $HIST ; do
    for v in $VARS ; do
#
# 850-899 first
#
      NUM=`ls ${c}.${h}.${v}.08??.nc | wc -l`
      if [ $NUM -eq 50 ] ; then
        Y0=0850
        Y1=0899
        case "$TPER" in
          ann )
            DF=CAT.${c}.${h}.${v}.${Y0}-${Y1}.nc ;;
          mon )
            DF=CAT.${c}.${h}.${v}.${Y0}01-${Y1}12.nc ;;
          day ) 
            DF=CAT.${c}.${h}.${v}.${Y0}0101-${Y1}1231.nc ;;
        esac
        echo -n "TS lme_year_to_cen of "${DF}" start: " ; date
        $NCRCAT -O ${c}.${h}.${v}.08??.nc $DF
        if [ $? = 0 ] ; then
          rm -f ${c}.${h}.${v}.08??.nc
          echo "Concatenated "$DF" and checked year count: 50"
          echo -n "TS lme_year_to_cen of "${DF}"   end: " ; date
        else
          echo "Failure on concat of "${c}"."${h}"."${v}" files"
          ./update_status error lme_year_to_cen
          exit 1
        fi
      else
        echo "Missing year(s) from "${c}"."${h}"."${v}".08??.nc files"
        echo "Count is "$NUM" should be 50"
        exit 1
      fi
#
# 900-1799 centuries
#
      for n in 09 10 11 12 13 14 15 16 17 ; do
        NUM=`ls ${c}.${h}.${v}.{n}??.nc | wc -l`
        if [ $NUM -eq 100 ] ; then
          Y0=${n}00
          Y1=${n}99
          case "$TPER" in
            ann )
              DF=CAT.${c}.${h}.${v}.${Y0}-${Y1}.nc ;;
            mon )
              DF=CAT.${c}.${h}.${v}.${Y0}01-${Y1}12.nc ;;
            day ) 
              DF=CAT.${c}.${h}.${v}.${Y0}0101-${Y1}1231.nc ;;
          esac
          echo -n "TS lme_year_to_cen of "${DF}" start: " ; date
          $NCRCAT -O ${c}.${h}.${v}.${n}??.nc $DF
          if [ $? = 0 ] ; then
            rm -f ${c}.${h}.${v}.${n}??.nc
            echo "Concatenated "$DF" and checked year count: 100"
            echo -n "TS lme_year_to_cen of "${DF}"   end: " ; date
          else
            echo "Failure on concat of "${c}"."${h}"."${v}" files"
            ./update_status error lme_year_to_cen
            exit 1
          fi
        else
          echo "Missing year(s) from "${c}"."${h}"."${v}"."${n}"??.nc files"
          echo "Count is "$NUM" should be 100"
          exit 1
        fi
      done
#
# 1800-1850 last
#
      NUM=`ls ${c}.${h}.${v}.18??.nc | wc -l`
      if [ $NUM -eq 51 ] ; then
        Y0=1800
        Y1=1850
        case "$TPER" in
          ann )
            DF=CAT.${c}.${h}.${v}.${Y0}-${Y1}.nc ;;
          mon )
            DF=CAT.${c}.${h}.${v}.${Y0}01-${Y1}12.nc ;;
          day ) 
            DF=CAT.${c}.${h}.${v}.${Y0}0101-${Y1}1231.nc ;;
        esac
        echo -n "TS lme_year_to_cen of "${DF}" start: " ; date
        $NCRCAT -O ${c}.${h}.${v}.18??.nc $DF
        if [ $? = 0 ] ; then
          rm -f ${c}.${h}.${v}.18??.nc
          echo "Concatenated "$DF" and checked year count: 51"
          echo -n "TS lme_year_to_cen of "${DF}"   end: " ; date
        else
          echo "Failure on concat of "${c}"."${h}"."${v}" files"
          ./update_status error lme_year_to_cen
          exit 1
        fi
      else
        echo "Missing year(s) from "${c}"."${h}"."${v}".18??.nc files"
        echo "Count is "$NUM" should be 51"
        exit 1
      fi
    done
  done
done
