#!/bin/sh
#
#PBS -N NAME
#PBS -q regular
#PBS -l mppwidth=144
#PBS -l walltime=48:00
#PBS -o log.NAME
#PBS -e log.NAME
#PBS -m abe
#PBS -V
#
eval `/opt/modules/3.2.10.3/bin/modulecmd sh load python/2.7.9`
eval `/opt/modules/3.2.10.3/bin/modulecmd sh load virtualenv/12.1.1`
eval `/opt/modules/3.2.10.3/bin/modulecmd sh load numpy/1.9.2`
eval `/opt/modules/3.2.10.3/bin/modulecmd sh load scipy/0.15.1`
eval `/opt/modules/3.2.10.3/bin/modulecmd sh load mpi4py/1.3.1`
eval `/opt/modules/3.2.10.3/bin/modulecmd sh load matplotlib/1.4.3`
eval `/opt/modules/3.2.10.3/bin/modulecmd sh load nco/4.3.9`
eval `/opt/modules/3.2.10.3/bin/modulecmd sh load ncl/6.1.1`
eval `/opt/modules/3.2.10.3/bin/modulecmd sh load cray-netcdf/4.3.2`
eval `/opt/modules/3.2.10.3/bin/modulecmd sh load cray-hdf5/1.8.13`
#
PYTHONPATH=/global/project/projectdirs/ccsm1/pythonlib/lib/python2.7/site-packages/PyNIO:$PYTHONPATH
export PYTHONPATH
