#!/bin/sh
#
#PBS -q serial
#PBS -l nodes=1
#PBS -l walltime=48:00:00
#PBS -N NAME
#PBS -m abe
#PBS -e log.NAME
#PBS -o log.NAME
#PBS -V
#
/opt/modules/default/init/sh
module load nco/4.3.9
module load cray-netcdf/4.3.2
module load cray-hdf5/1.8.13
#
