#!/bin/sh
#
#BSUB -n 16
#BSUB -R "span[ptile=4]"
#BSUB -q regular
#BSUB -a poe
#BSUB -q geyser
#BSUB -W 72:00
#BSUB -o log.NAME
#BSUB -e log.NAME
#BSUB -J NAME
#BSUB -P PROJNO
#BSUB -u USER@ucar.edu
#
export MP_TIMEOUT=14400
export MP_PULSE=1800
export MP_DEBUG_NOTIMEOUT=yes
#
# Necessary modules to load
#
eval `/glade/apps/opt/lmod/lmod/libexec/lmod bash load python`
eval `/glade/apps/opt/lmod/lmod/libexec/lmod bash load all-python-libs`
PATH=/glade/u/home/strandwg/.local/bin:${PATH} ; export PATH
#
