#!/bin/sh
# Read file(s) from a archival system
#
if [ $# -ne 2 ] ; then
  echo "Usage: mss_read MSSLIST YEARNOW"
  echo "Requires MSSLIST and YEARNOW"
  echo "CASE HISTNAM MSSHIST must be defined"
  exit 1
else
  MSSLIST=$1
  YEARNOW=$2
fi
#
if ! [ -f $MSSLIST ] ; then
  echo "mss_read: No "$MSSLIST" file found. Exit."
  exit 1
fi
if [ ! $CASE ] ; then
  echo "mss_read: CASE undefined. Exit."
fi
if [ ! $HISTNAM ] ; then
  echo "mss_read: HISTNAM undefined. Exit."
fi
if [ ! $MSSHIST ] ; then
  echo "mss_read: MSSHIST undefined. Exit."
fi
#
# Deduce files to read
#
if [ `echo $CASE | cut -d"_" -f1` = "cam3t42" ] ; then
  DAT=`/bin/egrep "$HISTNAM.$YEARNOW" $MSSLIST | cut -d"." -f4-`
else
  CHEK=`echo $CASE | egrep "\.ES"`
  if [ $? -eq 0 ] ; then
    DAT=`egrep "${HISTNAM}\.${YEARNOW}" $MSSLIST | cut -d"." -f6-`
  else
    DAT=`egrep "${HISTNAM}\.${YEARNOW}" $MSSLIST | cut -d"." -f5-`
  fi
fi
#
LST=`echo $DAT | sed -e "s/ /,/g"`
#
if [ `echo $LST | cut -d"." -f2` = "tar" ] ; then
  MSSFILES=$CASE.$HISTNAM.${LST}
else
  MSSFILES=$CASE.$HISTNAM."{"${LST}"}"
fi
#echo $MSSFILES
#
# If NCAR MSS msrcp command exists, use it.
TEST4MSRCP=`which msrcp 2<&1`
if [ $? -eq 0 ] ; then
   MSRCP=`which msrcp`
   $MSRCP -project 93300014 -overwrite sizemismatch mss:"$MSSHIST/$MSSFILES" .
   if [ $? -ne 0 ] ; then
     echo "Error on msrcp -overwrite sizemismatch mss:"$MSSHIST"/"$MSSFILES
     exit 1
   fi
#
# If NERSC/ORNL hsi command exists, use it.
else
  TEST4HSI=`which hsi 2<&1`
  if [ $? -eq 0 ] ; then
    if [ `echo $LST | cut -d"." -f2` = "tar" ] ; then
      htar -x -f $MSSHIST/$MSSFILES
      if [ $? -ne 0 ] ; then
        hsi -q "get -U $MSSHIST/$MSSFILES"
        if [ $? -eq 0 ] ; then
          tar xf $MSSFILES
          if [ $? -ne 0 ] ; then
            echo "htar and tar extraction failed on "$MSSFILES
            exit 1
          else
            rm -f  $MSSFILES
          fi
        else
          echo "Error on hsi get of "$MSSHIST"/"$MSSFILES
          exit 1
        fi
      fi
    else
      hsi -q "get $MSSHIST/$MSSFILES" 2>&1
      if [ $? -ne 0 ] ; then
        echo "Error on hsi get of "$MSSHIST"/"$MSSFILES
        exit 1
      fi
    fi
  else
    echo "Neither msrcp nor hsi exist."
    exit 1
  fi
fi
