#!/bin/sh
# List a directory on an archival system
# Arguments:
# 1 local file that has list
#
if [ $# -ne 1 ] ; then
  echo "Usage: mss_list local_list - REQUIRED"
  exit 1
else
  MSSL=$1
fi
#
# If NCAR MSS msrcp command exists, use it.
TEST4MSRCP=`which ncrcat 2<&1 >& /dev/null`
if [ $? -eq 0 ] ; then
   rm -f ABCXYZ
   msls -1R "$MSSHIST" >& ABCXYZ
   if [ $? -eq 0 ] ; then
     egrep "$HISTNAM" ABCXYZ >& $MSSL
     rm -f ABCXYZ
   else
     echo "Error on mss_list from "$MSSHIST
     exit 1
   fi
#
# If NERSC/ORNL hsi command exists, use it.
else
  TEST4HSI=`which hsi 2<&1 >& /dev/null`
  if [ $? -eq 0 ] ; then
    rm -f ABCXYZ
    hsi -q "ls -1 ${MSSHIST}" >& ABCXYZ
    if [ $? -eq 0 ] ; then
      egrep "$HISTNAME" ABCXYZ >& $MSSL
      rm -f ABCXYZ
    else
      echo "Error on mss_list from "$MSSHIST
      exit 1
    fi
  else
    echo "Neither msrcp nor hsi exist."
    exit 1
  fi
fi
