#!/bin/sh
# Read file(s) from a archival system
#
if [ $# -ne 2 ] ; then
  echo "Usage: mss_var_read ARCHIVE_PROC VARS"
  echo "Requires ARCHIVE_PROC and VARS"
  ./procstat.sh error mss_var_read
  exit 1
else
  ARCHIVE_PROC=$1
  VARS=$2
fi
#
if ! [ $ARCHIVE_PROC ] ; then
  echo "mss_var_read: "$ARCHIVE_PROC" undefined. Exit."
  ./procstat.sh error mss_var_read
  exit 1
fi
if [ ! $HIST ] ; then
  echo "mss_var_read: HIST undefined. Exit."
fi
if [ ! $VARS ] ; then
  echo "mss_var_read: VARS undefined. Exit."
fi
#
# Get files - check if hsi exists first
#
TEST4HSI=`which hsi 2>&1`
if [ $? -eq 0 ] ; then
  hsi -q "ls -d ${ARCHIVE_PROC}" > /dev/null 2>&1
  if [ $? -eq 0 ] ; then
    hsi -q "cd ${ARCHIVE_PROC} ; cget -u ${CASE}.${HIST}.{${VARS}}.*.nc"
    if [ $? -ne 0 ] ; then
      echo "Error on hsi get of "$ARCHIVE_PROC" files. Stopping."
      ./procstat.sh error mss_var_read
      exit 1
    fi
  else
    echo "Assuming files are already on disk, as "${ARCHIVE_PROC}" not found."
  fi
else
  echo "Cannot find hsi command."
  ./procstat.sh error mss_var_read
  exit 1
fi
