#!/bin/sh
# Write a file to a mass store
#
# Arguments:
# 1 file to write
# 2 directory on archival system to write file to
#
if [ $# = 2 ] ; then
  MSSF=$1
  MSSD=$2
else
  echo "I need two arguments:"
  echo "1) file to write"
  echo "2) directory on archival system to write file to"
  exit 1
fi
#
if [ ! -f $MSSF ] ; then
  echo $MMSF" not present, cannot write to the archival system"
  exit 1
fi
#
# If hsi command exists, use it.
#
TEST4HSI=`which hsi 2<&1`
if [ $? -eq 0 ] ; then
  HSI=`which hsi`
  $HSI -q "mkdir -m 775 -p $MSSD ; put -U ${MSSD}/${MSSF}" 2>&1
  if [ $? -eq 0 ] ; then
    echo ${MSSF}" written to "${MSSD}" and erased."
    rm -f $MSSF
  else
    $HSI -q "put ${MSSF}" 2>&1
    if [ $? -eq 0 ] ; then
      echo ${MSSF}" written to your HPSS HOME and erased."
      rm -f $MSSF
    else
      echo "Problem with HPSS on "${MSSF}". Stopping"
      exit 1
    fi
  fi      
else
#
# If NCAR MSS msrcp command exists, use it.
#
  TEST4MSRCP=`which msrcp 2<&1`
  if [ $? -eq 0 ] ; then
    MSRCP=`which msrcp`
#
# Check for total length > 128 characters and attempt to modify
#
    MSSR=${MSSF}
    TOTLEN=`echo ${MSSD}"/"${MSSF} | wc -c`
    if [ $TOTLEN -gt 128 ] ; then
      MSSR=`echo $MSSF | sed -e 's/track1\.//g'`
      echo "Total MSS pathname too long (over 128 characters)"
      echo "Renaming to "${MSSR}
    fi
    $MSRCP -pe 3652 -class reliability=economy -srcdelete $MSSF "mss:${MSSD}/${MSSR}"
    if [ $? -eq 0 ] ; then
      echo $MSSR" written to "${MSSD}/${MSSR}" and erased."
    else
      echo "Problem with storing "${MSSR}" to "${MSSD}". Stopping."
      exit 1
    fi
  else
    echo "Neither msrcp nor hsi exist."
    exit 1
  fi
fi
