#!/bin/sh
# List a directory on an archival system
# Arguments:
# 1 local file that has list
#
if [ $# -ne 1 ] ; then
  echo "Usage: mss_list local_list - REQUIRED"
  exit 1
else
  MSSL=$1
fi
#
# If NCAR MSS 'msls' command exists, use it.
#
TEST4MSLS=`which msls 2<&1`
if [ $? -eq 0 ] ; then
   rm -f ABCXYZ
   msls -1 "$MSSHIST" >& ABCXYZ
   if [ $? -eq 0 ] ; then
     egrep "\.${HIST}\." ABCXYZ >& $MSSL
     rm -f ABCXYZ
   else
     echo "Error on mss_list from "$MSSHIST
     exit 1
   fi
#
# If NERSC/ORNL hsi command exists, use it.
#
else
  TEST4HSI=`which hsi 2<&1`
  if [ $? -eq 0 ] ; then
    rm -f ABCXYZ
    hsi -q "cd $MSSHIST; ls -Fl" >& ABCXYZ
    if [ $? -eq 0 ] ; then
      egrep "\.${HIST}\." ABCXYZ | cut -c60- >& $MSSL
      rm -f ABCXYZ
    else
      echo "Error on mss_list from "$MSSHIST
      exit 1
    fi
  else
    echo "Neither msls nor hsi exist."
    exit 1
  fi
fi
