#!/bin/sh
# Read a file from a mass store
# Arguments:
# 1 place on mass store to read file from
# 2 file to read
#
if [ $# = 2 ] ; then
  MSSD=$1
  MSSF=$2
else
  echo "I need two arguments:"
  echo "1) place on mass store to read file from"
  echo "2) file(s) to read"
  exit 1
fi
#
# If NCAR MSS msrcp command exists, use it.
if [ `which msrcp | wc -w` -eq 1 ] ; then
   msrcp -overwrite sizemismatch mss:"$MSSD/$MSSF" .
else
#
# If NERSC/ORNL hsi command exists, use it.
if [ `which hsi | wc -w` -eq 1 ] ; then 
     hsi -q "get -U $MSSD/$MSSF"
   else
     echo "Neither msrcp nor hsi exist."
     exit 1
   fi
fi
#
