#!/bin/sh
# List a directory on an archival system
# Arguments:
# 1 local file that has list
#
if [ $# -ne 1 ] ; then
  echo "Usage: mss_list local_list - REQUIRED"
  exit 1
else
  MSSL=$1
fi
#
# If NCAR MSS msrcp command exists, use it.
if [ `which msrcp` ] ; then
   rm -f ABCXYZ
   msls -1R "$MSSHIST" >& ABCXYZ
   egrep "$HISTNAM" ABCXYZ >& $MSSL
   rm -f ABCXYZ
else
#
# If NERSC/ORNL hsi command exists, use it.
   if [ `which hsi` ] ; then 
     hsi -q "ls -1R ${MSSHIST}" | egrep $HISTNAME >& $MSSL
   else
     echo "Neither msrcp nor hsi exist."
     exit 1
   fi
fi
