#!/bin/sh
#
if [ $# -ne 3 ] ; then
   echo "Usage: ./Process_DP CASE HIST TPER"
   echo "All three arguments REQUIRED:"
   echo "1: CASE name"
   echo "2: HIST name - usually one of [cam2.h0 cam2.h1 cam2.h2 clm.h0 pop.h csim.h cice.h etc]"
   echo "3: TPER time period of above HIST type - must be one of [mon day hr6 hr3]"
   exit 1
elif [ $# -eq 3 ] ; then
   CASE=$1 ; export CASE
   HIST=$2 ; export HIST
   TPER=$3 ; export TPER
fi
#
# Set up a bunch of stuff
#
if [ $TPER != "mon" ] ; then
  if [ $TPER != "day" ] ; then
    if [ $TPER != "hr6" ] ; then
      if [ $TPER != "hr3" ] ; then
        echo "TPER must be one of [mon day hr6 hr3]"
        exit 1
      fi
    fi
  fi
fi
#
EXPFILE=${HOME}/CCP_Processing_Suite/experiments.txt ; export EXPFILE
if ! [ -f $EXPFILE ] ; then
  echo "Cannot find "$EXPFILE". EXIT"
  exit 1
fi
#
PROCHOST=`hostname`;export PROCHOST
#
# Start to build processing script
#
CCPS_SCRIPT=${CASE}_${HIST}_process.sh
rm -f $CCPS_SCRIPT
#
case "$PROCHOST" in 
  silver* | tramhill* | hurricane* | mirage0 | mirage1 | mirage2 | mirage5 | modeling1* | euclid* )  # NCAR and NERSC machines
    echo "#!/bin/sh" > $CCPS_SCRIPT
    cat ./process_dp_template | sed -e "s/xxxCASExxx/$CASE/g" \
                              | sed -e "s/xxxHISTxxx/$HIST/g" \
                              | sed -e "s/xxxTPERxxx/$TPER/g" \
                           >> $CCPS_SCRIPT ;;
  mirage3 | mirage4 )  # NCAR and NERSC machines
    cat ./LSF_batch > $CCPS_SCRIPT
    cat ./process_dp_template | sed -e "s/xxxCASExxx/$CASE/g" \
                              | sed -e "s/xxxHISTxxx/$HIST/g" \
                              | sed -e "s/xxxTPERxxx/$TPER/g" \
                           >> $CCPS_SCRIPT ;;
  lens* )                                  # lens @ ORNL
    cat ./ORNL_batch > $CCPS_SCRIPT
    cat ./process_dp_template | sed -e "s/xxxCASExxx/$CASE/g" \
                              | sed -e "s/xxxHISTxxx/$HIST/g" \
                              | sed -e "s/xxxTPERxxx/$TPER/g" \
                           >> $CCPS_SCRIPT ;;
  * )
    echo "Unable to build script because "$PROCHOST" unknown."
    ./procstat.sh error process_dp_template
    exit 1 ;;
esac
#
chmod +x $CCPS_SCRIPT
echo ""
echo $CCPS_SCRIPT" ready to run"
echo ""
#
echo "Run script now? (Y only, all else NO)"
read DORUN
#
if [ "$DORUN" = "Y" ] ; then
  echo "Running "${CCPS_SCRIPT}
  case "$PROCHOST" in
    lens* )
      ( /usr/bin/qsub ./${CCPS_SCRIPT} ) ;;
    mirage3 | mirage4 )
      ( SOME_LSF_COMMAND ./${CCPS_SCRIPT} ) ;;
    * )
      ( ./${CCPS_SCRIPT} > log.${CCPS_SCRIPT} 2>&1 & ) ;;
  esac
else
  echo "Will not run "${CCPS_SCRIPT}
fi
