#!/bin/sh
#
if [ $# -ne 3 ] ; then
   echo "Usage: ./Process_Setup CASE HIST TPER"
   echo "All three arguments REQUIRED:"
   echo "1: CASE name"
   echo "2: HIST name - usually one of [cam2.h0 cam2.h1 cam2.h2 clm.h0 pop.h csim.h cice.h etc]"
   echo "3: TPER time period of above HIST type - must be one of [mon day hr6 hr3 m30]"
   exit 1
elif [ $# -eq 3 ] ; then
   CASE=$1 ; export CASE
   HIST=$2 ; export HIST
   TPER=$3 ; export TPER
fi
#
# Set up a bunch of stuff
#
case "$TPER" in
  mon | day | hr6 | hr3 | m30 )
    echo ${TPER}" is known time period. Proceeding." ;;
  * ) 
    echo "Unable to continue because "$TPER" is unknown. Stopping."
    ./procstat.sh error Process_Setup
    exit 1 ;;
esac
#
# Extract information from "experiments.txt"
#
#  Columns   Field
#   1 -  40  CCSM case name
#  45 -  64  model_id (CCSM4, CESM-CAM5, CESM-BGC, CESM-CHEM, CESM-WACCM, CESM1-CAM5.1-FV2, etc)
#  65 -  66  Location (NC = NCAR; NE = NERSC; OR = ORNL)
#  70 -  84  Official MIP name, or very brief description (N/A if not applicable)
#  85 -  94  RIP code (cm5) or realization number (cm3) (N/A if not applicable)
#  95 -  99  MIP (cm3 or cm5) experiment (N/A if not applicable)
# 100 - 139  RUN_REFCASE (parent case)
# 140 - 154  RUN_REFDATE (branch date, yyyy-mm-dd)
# 155 - 164  years of experiment (YYYY if unknown)
# 165 - 174  GRID (resolution)
# 175 - 194  COMPSET (N/A if not applicable)
# 195 - 214  REPOTAG (N/A if not applicable)
# 215 - 234  Calendar dates of simulation execution (yyyy/mm-yyyy/mm)
# 235 - 244  MACH (hardware)
# 245 - end  DOUT_L_MSROOT (history file location on archive)
#
EXPFILE=${HOME}/CCP_Processing_Suite/experiments.txt ; export EXPFILE
if ! [ -f $EXPFILE ] ; then
  echo "Cannot find "$EXPFILE". EXIT"
  exit 1
fi
#
PROCHOST=`hostname`;export PROCHOST
#
# Build processing script
#
CCPS_SCRIPT=${CASE}_${HIST}_${TPER}_process.sh
rm -f $CCPS_SCRIPT
#
case "$PROCHOST" in 
  silver* | tramhill* | hurricane* | mirage* | modeling1* | euclid* )  # NCAR and NERSC machines
    echo "#!/bin/sh" > $CCPS_SCRIPT
    cat ./process_template | sed -e "s/xxxCASExxx/$CASE/g" \
                           | sed -e "s/xxxHISTxxx/$HIST/g" \
                           | sed -e "s/xxxTPERxxx/$TPER/g" \
                           >> $CCPS_SCRIPT ;;
  lens* )                                  # lens @ ORNL
    cat ./ORNL_batch > $CCPS_SCRIPT
    cat ./process_template | sed -e "s/xxxCASExxx/$CASE/g" \
                           | sed -e "s/xxxHISTxxx/$HIST/g" \
                           | sed -e "s/xxxTPERxxx/$TPER/g" \
                           >> $CCPS_SCRIPT ;;
  * )
    echo "Unable to build script because "$PROCHOST" unknown."
    ./procstat.sh error process_template
    exit 1 ;;
esac
#
chmod +x $CCPS_SCRIPT
echo ""
echo $CCPS_SCRIPT" ready to run"
echo ""
#
echo "Run script now? (Y only, all else NO)"
read DORUN
#
if [ "$DORUN" = "Y" ] ; then
  echo "Running "${CCPS_SCRIPT}
  case "$PROCHOST" in
    lens* )
      ( /usr/bin/qsub ./${CCPS_SCRIPT} ) ;;
    * )
      ( ./${CCPS_SCRIPT} > log.${CCPS_SCRIPT} 2>&1 & ) ;;
  esac
else
  echo "Will not run "${CCPS_SCRIPT}
fi
