#!/bin/sh
#
if [ $# -lt 3 ] ; then
   echo "Usage: ./Process_Setup CASE HIST TABLE [cmip5 vars]"
   echo "First three arguments REQUIRED:"
   echo "1: CASE name"
   echo "2: HIST name - usually one of [cam2.h0 cam.h0 cam2.h1 cam.h1 cam2.h2 cam.h2 clm.h0 pop.h csim.h cice.h etc]"
   echo "3: TABLE CMIP5 table to use - one of:"
   echo "   3hr 6hrLev 6hrPlev aero Amon day fx grids LImon Lmon Oclim OImon Omon Oyr"
   echo "   cf3hr cfDay cfMon cfOff cfSites"
   echo "4: OPTIONAL - list of CMIP5 variable names to process, set off by double quotes and blank delimited, e.g,."
   echo '   "tas ts va ts"'
   exit 1
elif [ $# -eq 3 ] ; then
   CASE=$1 ; export CASE
   HIST=$2 ; export HIST
   TABL=$3 ; export TABL
elif [ $# -eq 4 ] ; then
   CASE=$1 ; export CASE
   HIST=$2 ; export HIST
   TABL=$3 ; export TABL
   VARS=$4 ; export VARS
else
   echo "Usage: ./Process_Setup CASE HIST TABLE [cmip5 vars]"
   echo "First three arguments REQUIRED:"
   echo "1: CASE name"
   echo "2: HIST name - usually one of [cam2.h0 cam.h0 cam2.h1 cam.h1 cam2.h2 cam.h2 clm.h0 pop.h csim.h cice.h etc]"
   echo "3: TABLE CMIP5 table to use - one of:"
   echo "   3hr 6hrLev 6hrPlev aero Amon day fx grids LImon Lmon Oclim OImon Omon Oyr"
   echo "   cf3hr cfDay cfMon cfOff cfSites"
   echo "4: OPTIONAL - list of CMIP5 variable names to process, set off by double quotes and blank delimited, e.g,."
   echo '   "tas ts va ts"'
   exit 1
fi
#
# Set up a bunch of stuff
#
case "$TABL" in
  3hr | 6hrLev | 6hrPlev | aero | Amon | day | fx | grids | LImon | Lmon | Oclim | OImon | Omon | Oyr | cf3hr | cfDay | cfMon | cfOff | cfSite )
    echo ${TABL}" known CMIP5 table. Proceeding." ;;
  * ) 
    echo "Unable to continue because "$TABL" not known CMIP5 table. Stopping."
    ./procstat.sh error process_cmip5_template
    exit 1 ;;
esac
#
if [ ! $PATH ] ; then
  PATH=${HOME}/bin:/usr/local/hpss/bin
else
  PATH=${HOME}/bin:/usr/local/hpss/bin:${PATH}
fi
export PATH
#
EXPFILE=${HOME}/CCP_Processing_Suite/experiments.txt ; export EXPFILE
if ! [ -f $EXPFILE ] ; then
  echo "Cannot find "$EXPFILE". EXIT"
  exit 1
fi
#
# Start to build processing script
#
CMIP5_SCRIPT=${CASE}_${HIST}_${TABL}_process.sh
rm -f $CMIP5_SCRIPT
#
# Acquire PROCHOST
#
PROCHOST=`hostname`;export PROCHOST
#
if [ "$VARS" ] ; then
  case "$PROCHOST" in 
    silver* | tramhill* | hurricane* | mirage0 | mirage1 | mirage2 | mirage5 | modeling1* | euclid* )  # NCAR and NERSC machines
      echo "#!/bin/sh" > $CMIP5_SCRIPT
      cat ./process_cmip5_template | sed -e "s/xxxCASExxx/$CASE/g" \
                                   | sed -e "s/xxxHISTxxx/$HIST/g" \
                                   | sed -e "s/xxxTABLxxx/$TABL/g" \
                                   | sed -e "s/xxxVARSxxx/$VARS/g" \
                                   >> $CMIP5_SCRIPT ;;
    mirage3 | mirage4 )  # NCAR and NERSC machines
      cat ./LSF_batch | sed -e "s/NAME/$CMIP5_SCRIPT/g" | sed -e "s/USER/$USER/g" > $CMIP5_SCRIPT
      cat ./process_cmip5_template | sed -e "s/xxxCASExxx/$CASE/g" \
                                   | sed -e "s/xxxHISTxxx/$HIST/g" \
                                   | sed -e "s/xxxTABLxxx/$TABL/g" \
                                   | sed -e "s/xxxVARSxxx/$VARS/g" \
                                   >> $CMIP5_SCRIPT ;;
    lens* )                                  # lens @ ORNL
      cat ./ORNL_batch > $CMIP5_SCRIPT
      cat ./process_cmip5_template | sed -e "s/xxxCASExxx/$CASE/g" \
                                   | sed -e "s/xxxHISTxxx/$HIST/g" \
                                   | sed -e "s/xxxTABLxxx/$TABL/g" \
                                   | sed -e "s/xxxVARSxxx/$VARS/g" \
                                   >> $CMIP5_SCRIPT ;;
    * )
      echo "Unable to build script because "$PROCHOST" unknown."
      ./procstat.sh error process_cmip5_template
      exit 1 ;;
  esac
else
  case "$PROCHOST" in 
    silver* | tramhill* | hurricane* | mirage0 | mirage1 | mirage2 | mirage5 | modeling1* | euclid* )  # NCAR and NERSC machines
      echo "#!/bin/sh" > $CMIP5_SCRIPT
      cat ./process_cmip5_template | sed -e "s/xxxCASExxx/$CASE/g" \
                                   | sed -e "s/xxxHISTxxx/$HIST/g" \
                                   | sed -e "s/xxxTABLxxx/$TABL/g" \
                                   | sed -e "s/xxxVARSxxx//g" \
                                   >> $CMIP5_SCRIPT ;;
    mirage3 | mirage4 )  # NCAR and NERSC machines
      cat ./LSF_batch | sed -e "s/NAME/$CMIP5_SCRIPT/g" | sed -e "s/USER/$USER/g" > $CMIP5_SCRIPT
      cat ./process_cmip5_template | sed -e "s/xxxCASExxx/$CASE/g" \
                                   | sed -e "s/xxxHISTxxx/$HIST/g" \
                                   | sed -e "s/xxxTABLxxx/$TABL/g" \
                                   | sed -e "s/xxxVARSxxx//g" \
                                   >> $CMIP5_SCRIPT ;;
    lens* )                                  # lens @ ORNL
      cat ./ORNL_batch             >> $CMIP5_SCRIPT
      cat ./process_cmip5_template | sed -e "s/xxxCASExxx/$CASE/g" \
                                   | sed -e "s/xxxHISTxxx/$HIST/g" \
                                   | sed -e "s/xxxTABLxxx/$TABL/g" \
                                   | sed -e "s/xxxVARSxxx//g" \
                                   >> $CMIP5_SCRIPT ;;
    * )
      echo "Unable to build script because "$PROCHOST" unknown."
      ./procstat.sh error process_cmip5_template
      exit 1 ;;
  esac
fi
#
chmod +x $CMIP5_SCRIPT
echo ""
echo $CMIP5_SCRIPT" ready to run"
echo ""
#
echo "Run script now? (Y only, all else NO)"
read DORUN
#
if [ "$DORUN" = "Y" ] ; then
  echo "Running "${CMIP5_SCRIPT}
  case "$PROCHOST" in 
    silver* | tramhill* | hurricane* | mirage0 | mirage1 | mirage2 | mirage5 | euclid* | modeling1* )  # NCAR and NERSC machines interactive machines
      ( ./${CMIP5_SCRIPT} > log.${CMIP5_SCRIPT} 2>&1 & ) ;;
    lens* )                                  # lens @ ORNL
      ( /usr/bin/qsub ./${CMIP5_SCRIPT} ) ;;
    mirage3 | mirage4 )  # NCAR mirage LSF machines
      ( /fs/local/apps/lsf/8.0/linux2.6-glibc2.3-x86_64/bin/bsub < ./${CMIP5_SCRIPT} ) ;;
    * )
      echo "Unable to run script because "$PROCHOST" unknown."
      ./procstat.sh error process_cmip5_template
      exit 1 ;;
  esac
else
  echo "Will not run "${CMIP5_SCRIPT}
fi
