#!/bin/sh
#
if [ $# -ne 4 ] ; then
   echo "Usage: ./Process_Setup CASE HIST TPER [lm or ext]"
   echo "Four arguments REQUIRED:"
   echo "1: CASE name"
   echo "2: HIST name - usually one of [cam2.h0 cam.h0 cam2.h1 cam.h1 cam2.h2 cam.h2 clm.h0 pop.h csim.h cice.h rtm.h0 etc]"
   echo "3: TPER time period of above HIST type - must be one of [ann mon day hr6 hr3 hr1 m30]"
   echo "4: lm or ext - either 850-1849 period [lm] or 1850-2005 period [ext] to be processed"
   exit 1
else
   CASE=$1 ; export CASE
   HIST=$2 ; export HIST
   TPER=$3 ; export TPER
   LMEX=$3 ; export LMEX
fi
#
# Set up a bunch of stuff
#
case "$TPER" in
  ann | mon | day | hr6 )
    echo ${TPER}" is known time period. Proceeding." ;;
  * ) 
    echo "Unable to continue because "$TPER" is unknown. Stopping."
    exit 1 ;;
esac
#
EXPFILE=${HOME}/CCP_Processing_Suite/experiments.txt ; export EXPFILE
if ! [ -f $EXPFILE ] ; then
  echo "Cannot find "$EXPFILE". EXIT"
  exit 1
fi
#
TEMPLATE=process_lme_template
#
PROCHOST=`hostname`;export PROCHOST
#
# Build processing script
#
CCPS_SCRIPT=${CASE}_${HIST}_${TPER}_${LMEX}_process.sh
rm -f $CCPS_SCRIPT
#
case "$PROCHOST" in 
  yslogin* | geyser* )                     # yellowstone/geyser @ NCAR
    cat ./LSF_geyser  | sed -e "s/NAME/$CCPS_SCRIPT/g" | sed -e "s/USER/$USER/g" > $CCPS_SCRIPT
    cat ./${TEMPLATE} | sed -e "s/xxxCASExxx/$CASE/g" \
                      | sed -e "s/xxxHISTxxx/$HIST/g" \
                      | sed -e "s/xxxTPERxxx/$TPER/g" \
                      | sed -e "s/xxxLMEXxxx/$LMEX/g" \
                      >> $CCPS_SCRIPT ;;
  * )
    echo "Unable to build script because "$PROCHOST" unknown."
    exit 1 ;;
esac
#
chmod +x $CCPS_SCRIPT
echo ""
echo $CCPS_SCRIPT" ready to run"
echo ""
#
echo "Run script now? (Y only, all else NO)"
read DORUN
#
if [ "$DORUN" = "Y" ] ; then
  echo "Running "${CCPS_SCRIPT}
  /ncar/opt/lsf/8.3/linux2.6-glibc2.3-x86_64/bin/bsub < ./${CCPS_SCRIPT}
else
  echo "Will not run "${CCPS_SCRIPT}
fi
