#!/bin/sh
#
if [ $# -ne 4 ] ; then
   echo "Usage: ./Process_Setup CASE HIST TPER"
   echo "First three arguments REQUIRED:"
   echo "1: CASE name"
   echo "2: HIST name - usually one of [cam2.h0 cam.h0 cam2.h1 cam.h1 cam2.h2 cam.h2 clm.h0 pop.h csim.h cice.h rtm.h0 etc]"
   echo "3: TPER time period of above HIST type - must be one of [ann mon day hr6 hr3 hr1 m30]"
   echo "4: LENG either by year or all time samples - must be one of [byy all]"
   exit 1
else
   CASE=$1 ; export CASE
   HIST=$2 ; export HIST
   TPER=$3 ; export TPER
   LENG=$4 ; export LENG
fi
#
# Set up a bunch of stuff
#
case "$TPER" in
  ann | mon | day | hr6 | hr3 | hr1 | m30 )
    echo ${TPER}" is known time period. Proceeding." ;;
  * ) 
    echo "Unable to continue because "$TPER" is unknown. Stopping."
    exit 1 ;;
esac
#
case "$LENG" in
  byy | all )
    echo ${LENG}" is good length." ;;
  * ) 
    echo "Unable to continue because "$LENG" is unknown. Stopping."
    exit 1 ;;
esac
#
# Check for LME runs
#
EXPFILE=${HOME}/CCP_Processing_Suite/experiments.txt ; export EXPFILE
if ! [ -f $EXPFILE ] ; then
  echo "Cannot find "$EXPFILE". EXIT"
  exit 1
else
  MIPNAME=`egrep "^$CASE " $EXPFILE | cut -c105- | cut -d" " -f1`
  case "$MIPNAME" in 
    lme )
      TEMPLATE=process_lme_template ;;
    le5 )
      TEMPLATE=process_le5_template ;;
    atl )
      TEMPLATE=process_atl_template ;;
    pac )
      TEMPLATE=process_pac_template ;;
    yyg )
      TEMPLATE=process_yyg_template ;;
    * )
      TEMPLATE=process_template ;;
  esac
fi
#
PROCHOST=`hostname`;export PROCHOST
#
# Build processing script
#
CCPS_SCRIPT=${CASE}_${HIST}_${TPER}_process.sh
rm -f $CCPS_SCRIPT
#
case "$PROCHOST" in 
  silver* )  # Interactive machines
    echo "#!/bin/sh" > $CCPS_SCRIPT
    cat ./${TEMPLATE} | sed -e "s/xxxCASExxx/$CASE/g" \
                      | sed -e "s/xxxHISTxxx/$HIST/g" \
                      | sed -e "s/xxxTPERxxx/$TPER/g" \
                      | sed -e "s/xxxLENGxxx/$LENG/g" \
                      >> $CCPS_SCRIPT ;;
  yslogin* | geyser* )                     # yellowstone/geyser @ NCAR
    cat ./LSF_geyser  | sed -e "s/NAME/$CCPS_SCRIPT/g" \
                      | sed -e "s/USER/$USER/g"        \
                      | sed -e "s/PROJNO/P93300014/g"  \
                      > $CCPS_SCRIPT
    cat ./${TEMPLATE} | sed -e "s/xxxCASExxx/$CASE/g" \
                      | sed -e "s/xxxHISTxxx/$HIST/g" \
                      | sed -e "s/xxxTPERxxx/$TPER/g" \
                      | sed -e "s/xxxLENGxxx/$LENG/g" \
                      >> $CCPS_SCRIPT ;;
  rhea* )                                  # rhea @ ORNL
    cat ./LSF_rhea    > $CCPS_SCRIPT
    cat ./${TEMPLATE} | sed -e "s/xxxCASExxx/$CASE/g" \
                      | sed -e "s/xxxHISTxxx/$HIST/g" \
                      | sed -e "s/xxxTPERxxx/$TPER/g" \
                      | sed -e "s/xxxLENGxxx/$LENG/g" \
                      >> $CCPS_SCRIPT ;;
  nid* | hopper* | cvrsvc* )               # hopper/carver @ NERSC
    cat ./LSF_carver       | sed -e "s/NAME/$CCPS_SCRIPT/g" > $CCPS_SCRIPT
    cat ./${TEMPLATE} | sed -e "s/xxxCASExxx/$CASE/g" \
                      | sed -e "s/xxxHISTxxx/$HIST/g" \
                      | sed -e "s/xxxTPERxxx/$TPER/g" \
                      | sed -e "s/xxxLENGxxx/$LENG/g" \
                      >> $CCPS_SCRIPT ;;
  cooleylogin* | login1* )                                # tukey/cooley @ ANL
    cat ./LSF_tukey   | sed -e "s/NAME/$CCPS_SCRIPT/g" > $CCPS_SCRIPT
    cat ./${TEMPLATE} | sed -e "s/xxxCASExxx/$CASE/g" \
                      | sed -e "s/xxxHISTxxx/$HIST/g" \
                      | sed -e "s/xxxTPERxxx/$TPER/g" \
                      | sed -e "s/xxxLENGxxx/$LENG/g" \
                      >> $CCPS_SCRIPT ;;
  * )
    echo "Unable to build script because "$PROCHOST" unknown."
    exit 1 ;;
esac
#
chmod +x $CCPS_SCRIPT
echo ""
echo $CCPS_SCRIPT" ready to run"
echo ""
#
echo "Run script now? (Y only, all else NO)"
read DORUN
#
if [ "$DORUN" = "Y" ] ; then
  echo "Running "${CCPS_SCRIPT}
  case "$PROCHOST" in
    rhea* | hopper* | cvrsvc* )
      ( qsub ./${CCPS_SCRIPT} ) ;;
    yslogin* | geyser* )
      ( bsub < ./${CCPS_SCRIPT} ) ;;
    cooleylogin* | login1* )
      ( /usr/bin/qsub -n 1 -t 720 -A CESM_Atmos ./${CCPS_SCRIPT} ) ;;
    * )
      ( ./${CCPS_SCRIPT} > log.${CCPS_SCRIPT} 2>&1 & ) ;;
  esac
else
  echo "Will not run "${CCPS_SCRIPT}
fi
