#!/bin/sh
#
if [ $# -ne 4 ] ; then
   echo "Usage: ./Process_YY CASE HIST TPER (beg OR end)"
   echo "Three arguments REQUIRED:"
   echo "1: CASE name"
   echo "2: HIST name - usually one of [cam2.h0 cam.h0 cam2.h1 cam.h1 cam2.h2 cam.h2 clm.h0 pop.h csim.h cice.h rtm.h0 etc]"
   echo "3: TPER time period of above HIST type - must be one of [ann mon day hr6 hr3 hr1 m30]"
   echo "4: piece - BEG (2006-2100) or END (2101-2120) "
   exit 1
else
   CASE=$1 ; export CASE
   HIST=$2 ; export HIST
   TPER=$3 ; export TPER
   PIEC=$4 ; export PIEC
fi
#
# Set up a bunch of stuff
#
case "$TPER" in
  ann | mon | day | hr6 )
    echo ${TPER}" is known time period. Proceeding." ;;
  * ) 
    echo "Unable to continue because "$TPER" is unknown. Stopping."
    exit 1 ;;
esac
#
EXPFILE=${HOME}/CCP_Processing_Suite/experiments.txt ; export EXPFILE
if ! [ -f $EXPFILE ] ; then
  echo "Cannot find "$EXPFILE". EXIT"
  exit 1
else
  TEMPLATE=process_yyg_template
fi
#
PROCHOST=`hostname`;export PROCHOST
#
# Deduce appropriate node and ptile settings
#
case "$HIST" in
  cam.h1 ) 
    NODE=24
    TSKN=8 ;;
  * )
    NODE=16
    TSKN=4 ;;
  * )
    echo "Unknown "${HIST}
    exit 1 ;;
esac
#
# Build processing script
#
CCPS_SCRIPT=${CASE}_${HIST}_${TPER}_${PIEC}_process.sh
rm -f $CCPS_SCRIPT
#

cat ./LSF_YY      | sed -e "s/NAME/$CCPS_SCRIPT/g" \
                  | sed -e "s/USER/$USER/g"        \
                  | sed -e "s/NODE/$NODE/g"        \
                  | sed -e "s/TSKN/$TSKN/g"        \
                  | sed -e "s/PROJNO/P93300014/g"  > $CCPS_SCRIPT
#
cat ./${TEMPLATE} | sed -e "s/xxxCASExxx/$CASE/g" \
                  | sed -e "s/xxxHISTxxx/$HIST/g" \
                  | sed -e "s/xxxTPERxxx/$TPER/g" \
                  >> $CCPS_SCRIPT
#
chmod +x $CCPS_SCRIPT
echo ""
echo $CCPS_SCRIPT" ready to run"
echo ""
#
echo "Run script now? (Y only, all else NO)"
read DORUN
#
if [ "$DORUN" = "Y" ] ; then
  echo "Running "${CCPS_SCRIPT}
  case "$PROCHOST" in
    yslogin* | geyser* )
      ( bsub < ./${CCPS_SCRIPT} ) ;;
    * )
      echo "Unable to run script because not on yellowstone."
      exit 1 ;;
  esac
else
  echo "Will not run "${CCPS_SCRIPT}
fi
