#!/bin/sh
#
if [ $# -ne 4 ] ; then
   echo "Usage: ./Process_Setup CASE TYPE DO_PROC DO_IPCC"
   echo "All four arguments REQUIRED:"
   echo "1: Case name"
   echo "2: Type must be one of [atmm atmd lndm ocnm icem]"
   echo "3: Do single field processing [0 = NO, all other = YES]"
   echo "4: Do CMIP-style processing   [0 = NO, all other = YES]"
   exit 1
elif [ $# -eq 4 ] ; then
   CASE=$1 ; export CASE
   TYPE=$2 ; export TYPE
   PROC=$3 ; export PROC
   IPCC=$4 ; export IPCC
fi
#
# Set up a bunch of stuff
#
if [ $TYPE != "atmm" ] ; then
  if [ $TYPE != "atmd" ] ; then
    if [ $TYPE != "lndm" ] ; then
      if [ $TYPE != "ocnm" ] ; then
        if [ $TYPE != "icem" ] ; then
          echo "Type must be one of [atmm atmd lndm ocnm icem]"
          exit 1
        fi
      fi
    fi
  fi
fi
#
#
# Extract information from "experiments.txt"
#
#  Columns   Field
#   1 -  29  CCSM case name
#  30 -  31  Location (NC = NCAR; NE = NERSC; OR = ORNL)
#  35 -  49  Very brief description and/or PCMDI name (n/a if not applicable)
#  50 -  51  Realization number (2 digits) (0 if not applicable)
#  54 -  56  Is a CMIP3 (cm3) or CMIP5 (cm5) experiment?
#  60 -  80  Parent CCSM case name 
#  85 -  94  Branch date (yyyy-mm-dd, "none" if out-of-the-box)
# 100 - 103  Year began
# 105 - 108  Year ended
# 110 - 118  Resolution
# 120 - 129  Hardware
# 130 - end  History file location on archive
#
EXPFILE=${HOME}/CCP_Processing_Suite/experiments.txt ; export EXPFILE
if [ -f $EXPFILE ] ; then
  LOCATION=`egrep "^$CASE " $EXPFILE | cut -c30-  | cut -d" " -f1`
      CMIP=`egrep "^$CASE " $EXPFILE | cut -c54-56`
else
  echo "Cannot find "$EXPFILE". EXIT"
  exit 1
fi
#
if ! [ $LOCATION ] ; then
  echo "Unable to build script because case '"$CASE"' not found in "$EXPFILE
  exit 1
fi
#
# Start to build processing script
#
CCPS_SCRIPT=${CASE}_${TYPE}_process.sh
rm -f $CCPS_SCRIPT
#
case "$LOCATION" in
  NC )                                        # NCAR experiments
    echo "#!/bin/sh" > $CCPS_SCRIPT
    cat ./process_${CMIP}_template | sed -e "s/xxxCASExxx/$CASE/g" | sed -e "s/xxxTYPExxx/$TYPE/g" \
                                   | sed -e "s/xxxPROCxxx/$PROC/g" | sed -e "s/xxxIPCCxxx/$IPCC/g" \
                                   >> $CCPS_SCRIPT ;;
  NE )                                        # NERSC experiments
    cat ./batch_cmds_NERSC         >> $CCPS_SCRIPT
    cat ./process_${CMIP}_template | sed -e "s/xxxCASExxx/$CASE/g" | sed -e "s/xxxTYPExxx/$TYPE/g" \
                                   | sed -e "s/xxxPROCxxx/$PROC/g" | sed -e "s/xxxIPCCxxx/$IPCC/g" \
                                   >> $CCPS_SCRIPT ;;
  OR )                                        # ORNL experiments
    cat ./batch_cmds_ORNL          >> $CCPS_SCRIPT
    cat ./process_${CMIP}_template | sed -e "s/xxxCASExxx/$CASE/g" | sed -e "s/xxxTYPExxx/$TYPE/g" \
                                   | sed -e "s/xxxPROCxxx/$PROC/g" | sed -e "s/xxxIPCCxxx/$IPCC/g" \
                                   >> $CCPS_SCRIPT ;;
  * )
    echo "Unable to build script because "$LOCATION" not found in "$EXPFILE
    exit 1 ;;
esac
#
chmod +x $CCPS_SCRIPT
echo $CCPS_SCRIPT" ready to run"
#
exit
