#!/bin/sh
#
# Process CCSM history netCDF files into single-field format and/or IPCC format
#
# --------------------------------------------------------------------------------
# User-settable parameters
# --------------------------------------------------------------------------------
# Case(s)
#
CASELIST="b30.040c"
#
# Type(s) - one of "atmm atmd lndm ocnm icem"
#
TYPELIST="ocnm"
#
# Whether or not to do IPCC processing (zero means DO NOT, non-zero means DO)
#
DO_IPCC=0 ; export DO_IPCC
#
# Whether or not to do single-field processing (zero means DO NOT, non-zero means DO)
# one for each type above
#
DO_PROC=1 ; export DO_PROC
#
CURDIR=$PWD
#
for CASE in $CASELIST ; do
  export CASE
  for TYPE in $TYPELIST ; do
    export TYPE
# --------------------------------------------------------------------------------
# Set up all necessary script variables
# MUST BE "source"'D TO PASS VARIABLES!
# --------------------------------------------------------------------------------
#
    source ./process_setup
    if [ $? -ne 0 ] ; then
      echo "ERROR in setting up "$CASE" "$TYPE" processing. EXITING. FIX."
      exit 1
    fi
#
    cd $PROCDIR
    YEARNOW=$YEARBEG;export YEARNOW
    while [ $YEARNOW -le $YEAREND ] ; do
      YRCHECK=.comp.$CASE.$HISTNAM.$YEARNOW
      if [ ! -f $YRCHECK ] ; then
        echo "Processing "$CASE"."$HISTNAM"."$YEARNOW" at "`date`
        MSSLIST=MSS.$CASE.$TYPE
        if [ ! -f $MSSLIST ] ; then
          echo "Getting archival list of "$CASE" "$HISTNAM
          ./mss_list $MSSLIST
        fi
        ./mss_read $MSSLIST
        if [ $? -ne 0 ] ; then
          echo "Error from mss_read"
          exit 1
        else
          if [ "$TYPE" != "atmd" ] ; then
            for FILE in `ls $CASE.$HISTNAM.$YEARNOW-??.nc` ; do
              if [ $DO_IPCC -ne 0 ] ; then
                if [ "$TYPE" = "ocnm" ] || [ "$TYPE" = "icem" ] ; then
                  ./regrid_data $FILE
                  if [ $? -ne 0 ] ; then
                    echo "Error from regrid_data on file "$FILE
                    exit 1
                  else
                    for FINT in `ls $CASE.$HISTNAM.*.$YEARNOW-??.nc` ; do
                      ./create_ipcc_data $FINT
                      if [ $? -ne 0 ] ; then
                        echo "Error from create_ipcc_data on file "$FINT
                        exit 1
                      else
                        rm -f $FINT
                      fi
                    done
                    touch .ipcc.$FILE
                  fi
                else
                  ./create_ipcc_data $FILE
                  if [ $? -ne 0 ] ; then
                    echo "Error from create_ipcc_data on file "$FILE
                    exit 1
                  else
                    touch .ipcc.$FILE
                    if [ $DO_PROC -eq 0 ] ; then
                      rm -f $FILE
                    fi
                  fi
                fi
              fi
              if [ $DO_PROC -ne 0 ] ; then
                ./var_split $FILE erase
                if [ $? -ne 0 ] ; then
                  echo "Error from var_split on file "$FILE
                  exit 1
                else
                  touch .proc.$FILE
                fi
              fi
              if [ -f .proc.$FILE ] || [ -f .ipcc.$FILE ] ; then
                touch .comp.$FILE
                rm -f .proc.$FILE .ipcc.$FILE
              fi
            done
          else
            for FILE in `ls $CASE.$HISTNAM.${YEARNOW}*nc` ; do
              ./time_split $FILE erase
              ./days_to_month erase
            done
            for FILE in `ls $CASE.$HISTNAM.????-??.nc` ; do
              if [ $DO_IPCC -ne 0 ] ; then
                ./create_ipcc_data $FILE
                if [ $? -ne 0 ] ; then
                  echo "Error from create_ipcc_data on file "$FILE
                  exit 1
                else
                  touch .ipcc.$FILE
                fi
              fi
              if [ $DO_PROC -ne 0 ] ; then
                ./var_split $FILE erase
                if [ $? -ne 0 ] ; then
                  echo "Error from var_split on file "$FILE
                  exit 1
                else
                  touch .proc.$FILE
                fi
              fi
              if [ -f .proc.$FILE ] || [-f .ipcc.$FILE ] ; then
                touch .comp.$FILE
              fi
            done
          fi
        fi
        if [ `ls .comp.$CASE.$HISTNAM.$YEARNOW-??.nc | wc -l` -eq 12 ] ; then
          touch $YRCHECK
          rm .????.$CASE.$HISTNAM.$YEARNOW-??.nc
        fi
      fi
      YEARNOW=`expr $YEARNOW + 1`;export YEARNOW

    done
#
# Concatenate months -> years, years -> all (if possible)
#
    ./concatenate_data
#
# Store completed data on archival system
#
    ./store_to_archive
#
  cd $CURDIR
  done # TYPE
done # CASE
#
exit
