#!/bin/sh
#
# ASB - procstat script to monitor CCP_Processing_Suite as it runs
# from the script generated by Process_Setup
#
_DEBUG="on"
function DEBUG()
{
 [ "$_DEBUG" == "on" ] &&  $@
}

#echo "procstat : start"

# for debugging, hardcode - will get these from env. vars.
#
#CASE=b40.rcp2_6.2deg.001
#HIST=pop.h
#TPER=mon
#DO_PROC=1
#DO_CMIP=0
#LOCATION=NC
#ARCHIVE_PROC=/CCSM/csm/b40.rcp2_6.2deg.001/ocn/proc/tseries/monthly
#
# generate a base filename
#
#FILEBASE=${CASE}_${HIST}_${TPER}_${DO_PROC}_${DO_CMIP} ; export FILEBASE
FILEBASE=${CASE}.${HIST}.${TPER} ; export FILEBASE

#
# generate the filenames to be used
#
FILEPS=${FILEBASE}.ps ; export FILEPS
FILELOG=${FILEBASE}.log ; export FILELOG
FILEDF=${FILEBASE}.df ; export FILEDF
FILEHSI=${FILEBASE}.hsi; export FILEHSI

#
# get current user name
#
USER=`whoami`
#
# need to follow a naming convention for the logfiles
# execute and save to files
#
case "$PROCHOST" in
  copper* | mirage* | tramhill* | hurricane* | euclid* ) 
    LOGFILE=`ls ~/CCP_Processing_Suite/log*${CASE}*${HIST}*`
    date > ${FILEPS}
    ps auwx | grep ${USER} >> ${FILEPS} ;;
  lens* )
    LOGFILE=`ls ~/CCP_Processing_Suite/*.ER`
    date > ${FILEPS}
    qstat >> ${FILEPS}  ;;
  * )
#    echo "procstat : LOGFILE does not exist for "$LOCATION" - "$FILEBASE >>& log_${FILEBASE}
    ;;
esac

date > ${FILELOG}
tail -n 40 ${LOGFILE} >> ${FILELOG}

date > ${FILEDF}
df -h >> ${FILEDF}

#
# get the mass store listing to see where we are in the processing using $ARCHIVE_PROC
#
#
# If NCAR ARCHIVE_ msrcp command exists, use it.
date > $FILEHSI
TEST4MSLS=`which msls 2<&1`
if [ $? -eq 0 ] ; then
   rm -f tossme
   msls -l -project 93300014 -1R "$ARCHIVE_PROC" >& tossme
   if [ $? -eq 0 ] ; then
     egrep "\.${HIST}\." tossme >> $FILEHSI
     rm -f tossme
   else
     echo "procstat : (files may not have been written yet) Error on msls from "$ARCHIVE_PROC >> $FILEHSI
     rm -f tossme
   fi
#
# If NERSC/ORNL hsi command exists, use it.
else
  TEST4HSI=`which hsi 2<&1`
  if [ $? -eq 0 ] ; then
    rm -f tossme
    hsi -q "cd $ARCHIVE_PROC; ls -Fl" >& tossme
    if [ $? -eq 0 ] ; then
      egrep "\.${HIST}\." tossme | cut -c60- >> $FILEHSI
      rm -f tossme
    else
      echo "procstat : (files may not have been written yet) Error on hsi from "$ARCHIVE_PROC >> $FILEHSI
      rm -f tossme
    fi
  else
    echo "Neither msrcp nor hsi exist." >> $FILEHSI
  fi
fi


#
# create the mail messages
#
MAILTO=procstat@cgd.ucar.edu

mail -s "procstat ${FILEPS}" ${MAILTO} < ${FILEPS}
mail -s "procstat ${FILELOG}" ${MAILTO} < ${FILELOG}
mail -s "procstat ${FILEDF}" ${MAILTO} < ${FILEDF}
mail -s "procstat ${FILEHSI}" ${MAILTO} < ${FILEHSI}

DEBUG="off"

#echo "procstat : finish"
