#!/bin/sh
#
# Store data on archival system
#
if [ $# -ne 0 ] ; then
  echo "Usage: store_to_archive_keep"
  ./update_status error store_to_archive_keep
  exit 1
fi
# 
# Check for CACHEDIR
#
if [ ! $CACHEDIR ] ; then
  echo "CACHEDIR not defined. Exiting"
  ./update_status error store_to_archive_keep
  exit 1
fi
#
cd $CACHEDIR
#
if [ `/bin/ls *.nc | wc -l` -ne 0 ] ; then
  ../archive_write_keep $ARCHIVE_PROC
else
  echo "No files in "${CACHEDIR}". Exit."
  ./update_status error store_to_archive_keep
fi
#
cd $LOCAL_PROC
