#!/bin/sh
#
# Store data on archival system, one directory per field
#
if [ $# -ne 0 ] ; then
  echo "Usage: store_to_archive_var_keep"
  ./update_status error store_to_archive_var_keep
  exit 1
fi
# 
# Check for CACHEDIR/to_archive
#
if [ ! $CACHEDIR/to_archive ] ; then
  echo "CACHEDIR/to_archive not defined. Exiting"
  ./update_status error store_to_archive_var_keep
  exit 1
fi
#
cd $CACHEDIR/to_archive
#
if [ `/bin/ls *.nc | wc -l` -ne 0 ] ; then
  ../archive_write_var_keep
  if [ $? -ne 0 ] ; then
    echo "store_to_archive_var_keep failed"
    ./update_status error store_to_archive_var_keep
    exit 1
  fi
else
  echo "No files in "${CACHEDIR}"/to_archive. Exit."
  ./update_status error store_to_archive_var_keep
fi
#
cd $LOCAL_PROC
