#!/bin/sh
#
# Store data on archival system
#
if [ $# -ne 0 ] ; then
  echo "Usage: store_to_archive"
  exit 1
fi
#
cd $CACHEDIR
ln -s -f ${BASEDIR}/mss_write .
#
#
if [ $DO_PROC -ne 0 ] ; then
  LAST=`ls -1 $CASE.*nc | tail -1`
  while [ -f $LAST ] ; do
    for cfile in `ls CAT.${CASE}.*nc | head -5` ; do
      SFILE=`echo $cfile | sed -e 's/^CAT\.//g'`
      mv $cfile $SFILE
      ./mss_write $SFILE $MSSPROC &
    done
    wait
  done
fi
#
if [ $DO_CMIP -ne 0 ] ; then
  if [ "$CMIP" = "cm5" ] ; then
    LAST=`ls -1 *-*.nc | tail -1`
    while [ -f $LAST ] ; do
      for cfile in `ls *-*.nc | head -5` ; do
        ./mss_write $cfile $MSSCMIP &
      done
      wait
    done
  fi
  if [ "$CMIP" = "cm3" ] ; then
    LAST=`ls *nc | tail -1`
    while [ -f $LAST ] ; do
      for cfile in `ls *nc | head -5` ; do
        ./mss_write $cfile $MSSCMIP &
      done
      wait
    done
  fi
fi
