#!/bin/sh
#
if [ $# -eq 0 ] ; then
   echo "Usage: time_split file [erase]"
   echo "2 args means erase file after data split by time."
   ./procstat.sh error time_split
   exit 1
elif [ $# -eq 1 ] || [ $# -eq 2 ] ; then
   FILE=$1
else
   echo "Usage: time_split file [erase]"
   echo "2 args means erase file after data split by time."
   ./procstat.sh error time_split
   exit 1
fi
#
if [ ! -f $FILE ] ; then
  echo "File "$FILE" does not exist. Exit."
  ./procstat.sh error time_split
  exit 1
fi
# 
# Check for ncks
#
if [ ! $NCKS ] ; then
  TEST4NCKS=`which ncks 2>&1`
  if [ $? -eq 0 ] ; then
    NCKS=`which ncks`
  else
    echo "NCKS not in PATH - UNDEFINED"
    ./procstat.sh error time_split
    exit 1
  fi
fi
#
# Parse filename
#
FLEN=`echo $FILE | wc -c`
NDOT=0
CSTR=1
while [ $CSTR -le $FLEN ] ; do
  CURC=`echo $FILE | cut -c${CSTR}-${CSTR}`
  if [ "$CURC" = "." ] ; then
     NDOT=`expr '(' $NDOT ')' '+' '1'`
  fi
  CSTR=`expr '(' $CSTR ')' '+' '1'`
done
IDOT=1
DPFX=1
while [ $IDOT -le $NDOT ] ; do
  CURC=`echo $FILE | cut -d "." -f${IDOT}-${IDOT}`
  case "$CURC" in
    cam2 )
      DPFX=`expr '(' $IDOT ')' '+' '1'` ;;
    clm2 )
      DPFX=`expr '(' $IDOT ')' '+' '1'` ;;
    pop )
      DPFX=`expr '(' $IDOT ')' '+' '1'` ;;
    csim )
      DPFX=`expr '(' $IDOT ')' '+' '1'` ;;
  esac
  IDOT=`expr '(' $IDOT ')' '+' '1'`
done
OUTPFX=`echo $FILE | cut -d"." -f1-${DPFX}`
DCMP=`expr '(' $DPFX ')' '-' '1'`
COMP=`echo $FILE | cut -d"." -f${DCMP}`
#
NT=`$NCKS -M $FILE | egrep "Record" | cut -d"=" -f3`
#
if [ "$COMP" = "cam2" ] ; then
  $NCKS -s "%8.8i\n" -F -H -C -v date $FILE | head -n ${NT} > T.${FILE}
  LT=`cat T.${FILE} | uniq`
  for it in $LT ; do
    D0=`egrep -n ${it} T.${FILE} | head -1 | cut -d":" -f1`
    D1=`egrep -n ${it} T.${FILE} | tail -1 | cut -d":" -f1`
    DT=${it}
    OF=$OUTPFX.$DT.nc
    $NCKS -h -O -F -d time,${D0},${D1} $FILE $OF
    if [ $? -ne  0 ] ; then
      echo "Error on "$NCKS" -O -F -d time,"$D0","$DT" "$FILE" "$OF
      ./procstat.sh error time_split
      exit 1
    fi
  done
  rm -f T.${FILE}
fi
#
if [ "$COMP" = "clm2" ] ; then
  IT=1
  while [ $IT -le $NT ] ; do
    TM=`$NCKS -s "%8.8i\n" -F -H -C -v mcdate -d time,${IT},${IT} $FILE`
    DS=`$NCKS -s "%5.5i\n" -F -H -C -v mcsec  -d time,${IT},${IT} $FILE`
    DT=${TM}"-"${DS}
    OF=$OUTPFX.$DT.nc
    $NCKS -h -O -F -d time,${IT},${IT} $FILE $OF
    if [ $? -eq  0 ] ; then
      IT=`expr $IT '+' '1'`
    else
      echo "Error on "$NCKS" -O -F -d time,"$IT","$IT" "$FILE" "$OF
      ./procstat.sh error time_split
      exit 1
    fi
  done
fi
if [ $# -eq 2 ] ; then
  rm -f $FILE
fi
