#!/bin/sh
#
# Concatenate months of by-field netCDF files into years
#
if [ $# -ne 0 ] ; then
  echo "Usage: var_year_to_dec"
  exit 1
fi
# 
# Check for ncrcat
#
if [ ! $NCRCAT ] ; then
  TEST4NCRCAT=`which ncrcat 2>&1`
  if [ $? -eq 0 ] ; then
    NCRCAT=`which ncrcat`
  else
    echo "NCRCAT not in PATH - UNDEFINED"
    exit 1
  fi
fi
# 
# Check for TPER
#
if [ ! $TPER ] ; then
  echo "TPER undefined. Assume daily"
  TPER="day" ; export TPER
fi
#
# Parse first filename
#
FILE=`ls | egrep "*.${HIST}.*.nc" | head -1`
FLEN=`echo $FILE | wc -c`
NDOT=0
CSTR=1
while [ $CSTR -le $FLEN ] ; do
  CURC=`echo $FILE | cut -c${CSTR}-${CSTR}`
  if [ "$CURC" = "." ] ; then
     NDOT=`expr '(' $NDOT ')' '+' '1'`
  fi
  CSTR=`expr '(' $CSTR ')' '+' '1'`
done
IDOT=1
DCAS=1
DVAR=1
DHT1=1
DHT2=1
while [ $IDOT -le $NDOT ] ; do
  CURC=`echo $FILE | cut -d "." -f${IDOT}-${IDOT}`
  case "$CURC" in
    cam2 | clm2 | pop | csim | cice )
      DCAS=`expr '(' $IDOT ')' '-' '1'`
      DVAR=`expr '(' $IDOT ')' '+' '1'`
      DHT1=$IDOT ;;
  esac
  IDOT=`expr '(' $IDOT ')' '+' '1'`
done
DHT2=`expr '(' $DHT1 ')' '+' '1'`
DVAR=`expr '(' $DVAR ')' '+' '1'`
DTIM=`expr '(' $DVAR ')' '+' '1'`
#
CASES=`ls | egrep '\.....\.nc$' | cut -d"." -f1-${DCAS} | sort | uniq`
 VARS=`ls | egrep '\.....\.nc$' | cut -d"." -f${DVAR} | sort | uniq`
 HIST=`ls | egrep '\.....\.nc$' | cut -d"." -f${DHT1},${DHT2} | sort | uniq`
for c in $CASES ; do      
  for h in $HIST ; do
    for v in $VARS ; do
      DECS=`ls | egrep "${c}\.${h}\.${v}\.....\.nc" | cut -d"." -f${DTIM} | cut -c1-3 | sort | uniq`
      for d in $DECS ; do
        NUM=`ls ${c}.${h}.${v}.${d}?.nc | wc -l`
        if [ $NUM -eq 10 ] ; then
          if [ "$TPER" = "mon" ] ; then 
            DF=CAT.${c}.${h}.${v}.${d}001-${d}912.nc
          fi
          if [ "$TPER" = "day" ] ; then 
            DF=CAT.${c}.${h}.${v}.${d}00101-${d}91231.nc
          fi
          if [ "$TPER" = "hr6" ] ; then 
            DF=CAT.${c}.${h}.${v}.${d}0010100Z-${d}9123118Z.nc
          fi
          if [ "$TPER" = "hr3" ] ; then 
            DF=CAT.${c}.${h}.${v}.${d}0010100Z-${d}9123121Z.nc
          fi
          if [ $DF ] ; then
            $NCRCAT -O ${c}.${h}.${v}.${d}?.nc $DF
            if [ $? -eq 0 ] ; then
              rm -f ${c}.${h}.${v}.${d}?.nc
            fi
          else
            echo "Undefined DF: "$DF
            exit 1
          fi
        fi
      done
    done
  done
done
