#!/bin/sh
#
# Concatenate years of by-field CCSM netCDF into whole span
#
if [ $# -ne 0 ] ; then
  echo "Usage: var_year_to_all"
  echo "Can use YRCOUNT as defined by process_setup"
  ./status_check error var_year_to_all
  exit 1
fi
# 
# Check for ncrcat
#
if [ ! $NCRCAT ] ; then
  TEST4NCRCAT=`which ncrcat 2>&1`
  if [ $? -eq 0 ] ; then
    NCRCAT=`which ncrcat`
  else
    echo "NCRCAT not in PATH - UNDEFINED"
    ./status_check error var_year_to_all
    exit 1
  fi
fi
# 
# Check for ncrcat
#
if [ ! $TPER ] ; then
  echo "TPER undefined. Assume monthly"
  TPER="mon" ; export TPER
fi
#
# Parse first filename
#
FILE=`ls | egrep '\.([0-9][0-9][0-9][0-9]|[0-9][0-9][0-9][0-9][0-9])\.nc$' | head -n 1`
FLEN=`echo $FILE | wc -c`
NDOT=0
CSTR=1
while [ $CSTR -le $FLEN ] ; do
  CURC=`echo $FILE | cut -c${CSTR}-${CSTR}`
  if [ "$CURC" = "." ] ; then
     NDOT=`expr '(' $NDOT ')' '+' '1'`
  fi
  CSTR=`expr '(' $CSTR ')' '+' '1'`
done
IDOT=1
DCAS=1
DVAR=1
DHT1=1
DHT2=1
while [ $IDOT -le $NDOT ] ; do
  CURC=`echo $FILE | cut -d "." -f${IDOT}-${IDOT}`
  case "$CURC" in
    cam2 | cam | clm2 | pop | csim | cice | rtm )
      DCAS=`expr '(' $IDOT ')' '-' '1'`
      DVAR=`expr '(' $IDOT ')' '+' '1'`
      DHT1=$IDOT ;;
  esac
  IDOT=`expr '(' $IDOT ')' '+' '1'`
done
#
DCMP=$DHT1
COMP=`echo $FILE | cut -d"." -f${DCMP}`
#
DHT2=`expr '(' $DHT1 ')' '+' '1'`
DVAR=`expr '(' $DVAR ')' '+' '1'`
DTIM=`expr '(' $DVAR ')' '+' '1'`
#
CASES=`ls | egrep '\.([0-9][0-9][0-9][0-9]|[0-9][0-9][0-9][0-9][0-9])\.nc$' | cut -d"." -f1-${DCAS} | sort | uniq`
 VARS=`ls | egrep '\.([0-9][0-9][0-9][0-9]|[0-9][0-9][0-9][0-9][0-9])\.nc$' | cut -d"." -f${DVAR} | sort | uniq`
 HIST=`ls | egrep '\.([0-9][0-9][0-9][0-9]|[0-9][0-9][0-9][0-9][0-9])\.nc$' | cut -d"." -f${DHT1}-${DHT2} | sort | uniq`
 COMP=`ls | egrep '\.([0-9][0-9][0-9][0-9]|[0-9][0-9][0-9][0-9][0-9])\.nc$' | cut -d"." -f${DCMP} | sort | uniq`
#
# Check for pop.h.nday1/h2/ecosys
#
if [ "$HIST" = "pop.h" ] ; then
  DYCK=`expr '(' $DHT2 ')' '+' '1'`
  ODAY=`ls | egrep '\.([0-9][0-9][0-9][0-9]|[0-9][0-9][0-9][0-9][0-9])\.nc$' | cut -d"." -f${DYCK} | sort | uniq`
  if [ "$ODAY" = "nday1" ] || [ "$ODAY" = "h2" ] ; then
    DHT2=$DYCK
    DVAR=`expr '(' $DVAR ')' '+' '1'`
    DTIM=`expr '(' $DVAR ')' '+' '1'`
    VARS=`ls | egrep '\.([0-9][0-9][0-9][0-9]|[0-9][0-9][0-9][0-9][0-9])\.nc$' | cut -d"." -f${DVAR} | sort | uniq`
    HIST=`ls | egrep '\.([0-9][0-9][0-9][0-9]|[0-9][0-9][0-9][0-9][0-9])\.nc$' | cut -d"." -f${DHT1}-${DHT2} | sort | uniq`
  fi
  if [ "$ODAY" = "ecosys" ] ; then
    DHT2=$DYCK
    DHT2=`expr '(' $DHT2 ')' '+' '1'`
    DVAR=`expr '(' $DVAR ')' '+' '2'`
    DTIM=`expr '(' $DVAR ')' '+' '1'`
    VARS=`ls | egrep '\.([0-9][0-9][0-9][0-9]|[0-9][0-9][0-9][0-9][0-9])\.nc$' | cut -d"." -f${DVAR} | sort | uniq`
    HIST=`ls | egrep '\.([0-9][0-9][0-9][0-9]|[0-9][0-9][0-9][0-9][0-9])\.nc$' | cut -d"." -f${DHT1}-${DHT2} | sort | uniq`
  fi
fi
#
for c in $CASES ; do
  for h in $HIST ; do
    for v in $VARS ; do
      if [ $YRCOUNT ] ; then
        NUM=`ls ${c}.${h}.${v}.*.nc | wc -l`
        if [ $NUM = $YRCOUNT ] ; then
          Y0=`ls ${c}.${h}.${v}.*.nc | head -n 1 | cut -d"." -f${DTIM}`
          Y1=`ls ${c}.${h}.${v}.*.nc | tail -n 1 | cut -d"." -f${DTIM}`
          if [ "$TPER" = "ann" ] ; then 
            DF=CAT.${c}.${h}.${v}.${Y0}-${Y1}.nc
          fi
          if [ "$TPER" = "mon" ] ; then 
            DF=CAT.${c}.${h}.${v}.${Y0}01-${Y1}12.nc
          fi
          if [ "$TPER" = "day" ] ; then 
            DF=CAT.${c}.${h}.${v}.${Y0}0101-${Y1}1231.nc
          fi
          if [ "$TPER" = "hr6" ] ; then 
            DF=CAT.${c}.${h}.${v}.${Y0}010100Z-${Y1}123118Z.nc
          fi
          if [ "$TPER" = "hr3" ] ; then 
            DF=CAT.${c}.${h}.${v}.${Y0}010100Z-${Y1}123121Z.nc
          fi
          if [ "$TPER" = "m30" ] ; then 
            DF=CAT.${c}.${h}.${v}.${Y0}001010000Z-${Y1}12312330Z.nc
          fi
          $NCRCAT -O ${c}.${h}.${v}.*.nc $DF
          if [ $? = 0 ] ; then
            rm -f ${c}.${h}.${v}.*.nc
            echo "Concatenated "$DF" and checked year count: "$YRCOUNT
          else
            echo "Failure on concat of "${c}"."${h}"."${v}" files"
	    ./status_check error var_year_to_all
            exit 1
          fi
        else
          echo "Missing year(s) from "${c}"."${h}"."${v}" files"
          echo "Count is "$NUM" should be "$YRCOUNT
        fi
      else
        Y0=`ls ${c}.${h}.${v}.*.nc | head -n 1 | cut -d"." -f${DTIM}`
        Y1=`ls ${c}.${h}.${v}.*.nc | tail -n 1 | cut -d"." -f${DTIM}`
        if [ "$TPER" = "ann" ] ; then 
          DF=CAT.${c}.${h}.${v}.${Y0}-${Y1}.nc
        fi
        if [ "$TPER" = "mon" ] ; then 
          DF=CAT.${c}.${h}.${v}.${Y0}01-${Y1}12.nc
        fi
        if [ "$TPER" = "day" ] ; then 
          DF=CAT.${c}.${h}.${v}.${Y0}0101-${Y1}1231.nc
        fi
        if [ "$TPER" = "hr6" ] ; then 
          DF=CAT.${c}.${h}.${v}.${Y0}010100Z-${Y1}123118Z.nc
        fi
        if [ "$TPER" = "hr3" ] ; then 
          DF=CAT.${c}.${h}.${v}.${Y0}010100Z-${Y1}123121Z.nc
        fi
        if [ "$TPER" = "m30" ] ; then 
          DF=CAT.${c}.${h}.${v}.${Y0}001010000Z-${Y1}12312330Z.nc
        fi
        $NCRCAT -O ${c}.${h}.${v}.*.nc $DF
        if [ $? = 0 ] ; then
          rm -f ${c}.${h}.${v}.*.nc
          echo "Concatenated "$DF" and WITHOUT checking year count"
        else
          echo "Failure on concat of "${c}"."${h}"."${v}" files"
	  ./status_check error var_year_to_all
          exit 1
        fi
      fi
    done
  done
done
