#!/bin/sh
#
# Concatenate years of by-field netCDF files into decades
#
if [ $# -ne 0 ] ; then
  echo "Usage: var_year_to_dec"
  exit 1
fi
#
CHEK=`ls b*.*.h*.*.????.nc | cut -d"." -f3 | cut -c1-2 | uniq`
for m in $CHEK ; do
  if [ $m = "ES" ] ; then
    FC=3 ; FV=6 ; FT=7 ; FD=4 ; FE=5
  else
    FC=2 ; FV=5 ; FT=6 ; FD=3 ; FE=4
  fi
  COMP=`ls b*.*.*.h*.*.????.nc | cut -d"." -f${FD}-${FE} | uniq`
  for p in $COMP ; do
    VARS=`ls b*.*.${p}.*.????.nc | cut -d"." -f${FV} | uniq`
    for v in $VARS ; do
      CASES=`ls b*.*.${p}.${v}.????.nc | cut -d"." -f1-${FC} | uniq`
      for c in $CASES ; do      
        DECS=`ls ${c}.${p}.${v}.????.nc | cut -d"." -f${FT} | cut -c1-3 | uniq`
        for d in $DECS ; do
          NUM=`ls ${c}.${p}.${v}.${d}?.nc | wc -l`
          if [ $NUM = 10 ] ; then
            if [ ${p} = "cam2.h1" ] ; then
              DF=${c}.${p}.${v}.${d}0-01-01_cat_${d}9-12-31.nc
            else
              DF=${c}.${p}.${v}.${d}0-01_cat_${d}9-12.nc
            fi
            if [ $DF ] ; then
              $CCPS_NCRCAT -h -O ${c}.${p}.${v}.${d}?.nc $DF
              if [ $? = 0 ] ; then
                rm -f ${c}.${p}.${v}.${d}?.nc
              fi
            else
              echo "Undefined DF: "$DF
            fi
          fi
        done
      done
    done
  done
done
