#!/bin/sh
#
# Concatenate years of by-field CCSM netCDF into whole span
#
if [ $# -ne 0 ] ; then
  echo "Usage: var_mon_to_year"
  echo "Can use YRCOUNT as defined by process_setup"
  exit 1
fi
# 
# Check for ncrcat
#
if [ ! $NCRCAT ] ; then
  TEST4NCRCAT=`which ncrcat 2>&1`
  if [ $? -eq 0 ] ; then
    NCRCAT=`which ncrcat`
  else
    echo "NCRCAT not in PATH - UNDEFINED"
    exit 1
  fi
fi
#
# Parse first filename
#
FILE=`ls | egrep '\.....\.nc$' | head -1`
FLEN=`echo $FILE | wc -c`
NDOT=0
CSTR=1
while [ $CSTR -le $FLEN ] ; do
  CURC=`echo $FILE | cut -c${CSTR}-${CSTR}`
  if [ "$CURC" = "." ] ; then
     NDOT=`expr '(' $NDOT ')' '+' '1'`
  fi
  CSTR=`expr '(' $CSTR ')' '+' '1'`
done
IDOT=1
DCAS=1
DVAR=1
DHT1=1
DHT2=1
while [ $IDOT -le $NDOT ] ; do
  CURC=`echo $FILE | cut -d "." -f${IDOT}-${IDOT}`
  case "$CURC" in
    cam2 | clm2 | pop | csim | cice )
      DCAS=`expr '(' $IDOT ')' '-' '1'`
      DVAR=`expr '(' $IDOT ')' '+' '1'`
      DHT1=$IDOT ;;
  esac
  IDOT=`expr '(' $IDOT ')' '+' '1'`
done
DCMP=$DHT1
DHT2=`expr '(' $DHT1 ')' '+' '1'`
DVAR=`expr '(' $DVAR ')' '+' '1'`
DTIM=`expr '(' $DVAR ')' '+' '1'`
#
CASES=`ls | egrep '\.....\.nc$' | cut -d"." -f1-${DCAS} | sort | uniq`
 VARS=`ls | egrep '\.....\.nc$' | cut -d"." -f${DVAR} | sort | uniq`
 HTAP=`ls | egrep '\.....\.nc$' | cut -d"." -f${DHT1},${DHT2} | sort | uniq`
 COMP=`ls | egrep '\.....\.nc$' | cut -d"." -f${DCMP} | sort | uniq`
#
for c in $CASES ; do
  for h in $HTAP ; do
    for v in $VARS ; do
      if [ $YRCOUNT ] ; then
        NUM=`ls ${c}.${h}.${v}.????.nc | wc -l`
        if [ $NUM = $YRCOUNT ] ; then
          Y0=`ls ${c}.${h}.${v}.????.nc | head -1 | cut -d"." -f${DTIM}`
          Y1=`ls ${c}.${h}.${v}.????.nc | tail -1 | cut -d"." -f${DTIM}`
          if [ $h = "cam2.h1" ] ; then
            DF=${c}.${h}.${v}.${Y0}0101-${Y1}1231.nc
          else
            DF=${c}.${h}.${v}.${Y0}01-${Y1}12.nc
          fi
          if [ "$COMP" = "cice" ] ; then
            DF=${c}.${h}.${v}_nh.${Y0}01-${Y1}12.nc
            $NCRCAT -d nj,280,383 -O ${c}.${h}.${v}.????.nc $DF
            if [ $? = 0 ] ; then
              echo "Concatenated "$DF" and checked year count: "$YRCOUNT
              DF=${c}.${h}.${v}_sh.${Y0}01-${Y1}12.nc
              $NCRCAT -d nj,0,75 -O ${c}.${h}.${v}.????.nc $DF
              if [ $? = 0 ] ; then
                echo "Concatenated "$DF" and checked year count: "$YRCOUNT
                rm -f ${c}.${h}.${v}.????.nc
              else 
                echo "Failure on concat of "${c}"."${h}"."${v}" SH files"
                exit 1
              fi
            else 
              echo "Failure on concat of "${c}"."${h}"."${v}" NH files"
              exit 1
            fi
          else
            $NCRCAT -O ${c}.${h}.${v}.????.nc $DF
            if [ $? = 0 ] ; then
              rm -f ${c}.${h}.${v}.????.nc
              echo "Concatenated "$DF" and checked year count: "$YRCOUNT
            else
              echo "Failure on concat of "${c}"."${h}"."${v}" files"
              exit 1
            fi
          fi
        else
          echo "Missing year(s) from "${c}"."${h}"."${v}" files"
          echo "Count is "$NUM" should be "$YRCOUNT
#          exit 1
        fi
      else
        Y0=`ls ${c}.${h}.${v}.????.nc | head -1 | cut -d"." -f${DTIM}`
        Y1=`ls ${c}.${h}.${v}.????.nc | tail -1 | cut -d"." -f${DTIM}`
        if [ $h = "cam2.h1" ] ; then
          DF=${c}.${h}.${v}.${Y0}0101-${Y1}1231.nc
        else
          DF=${c}.${h}.${v}.${Y0}01-${Y1}12.nc
        fi
        if [ "$COMP" = "cice" ] ; then
          DF=${c}.${h}.${v}_nh.${Y0}01-${Y1}12.nc
          $NCRCAT -d nj,280,383 -O ${c}.${h}.${v}.????.nc $DF
          if [ $? = 0 ] ; then
            echo "Concatenated "$DF" and WITHOUT checking year count"
            DF=${c}.${h}.${v}_sh.${Y0}01-${Y1}12.nc
            $NCRCAT -d nj,0,75 -O ${c}.${h}.${v}.????.nc $DF
            if [ $? = 0 ] ; then
              echo "Concatenated "$DF" and WITHOUT checking year count"
              rm -f ${c}.${h}.${v}.????.nc
            else 
              echo "Failure on concat of "${c}"."${h}"."${v}" SH files"
              exit 1
            fi
          else 
            echo "Failure on concat of "${c}"."${h}"."${v}" NH files"
            exit 1
          fi
        else
          $NCRCAT -O ${c}.${h}.${v}.????.nc $DF
          if [ $? = 0 ] ; then
            rm -f ${c}.${h}.${v}.????.nc
            echo "Concatenated "$DF" and WITHOUT checking year count"
          else
            echo "Failure on concat of "${c}"."${h}"."${v}" files"
            exit 1
          fi
        fi
      fi
    done
  done
done
