#!/bin/sh
#
# Concatenate years of by-field CCSM netCDF from LME pop.h into 100-year-long segments
#
if [ $# -ne 0 ] ; then
  echo "Usage: var_lme_year_to_cen"
  ./update_status error var_lme_year_to_cen
  exit 1
fi
# 
# Check for ncrcat
#
if [ ! $NCRCAT ] ; then
  TEST4NCRCAT=`which ncrcat 2>&1`
  if [ $? -eq 0 ] ; then
    NCRCAT=`which ncrcat`
  else
    echo "NCRCAT not in PATH - UNDEFINED"
    ./update_status error var_lme_year_to_cen
    exit 1
  fi
fi
# 
# Check for ncrcat
#
if [ ! $TPER ] ; then
  echo "TPER undefined. Assume monthly"
  TPER="mon" ; export TPER
fi
#
# Parse first filename
#
FILE=`ls | egrep '\.[0-9][0-9][0-9][0-9]\.nc$' | head -n 1`
FLEN=`echo $FILE | wc -c`
NDOT=0
CSTR=1
while [ $CSTR -le $FLEN ] ; do
  CURC=`echo $FILE | cut -c${CSTR}-${CSTR}`
  if [ "$CURC" = "." ] ; then
     NDOT=`expr '(' $NDOT ')' '+' '1'`
  fi
  CSTR=`expr '(' $CSTR ')' '+' '1'`
done
IDOT=1
DCAS=1
DVAR=1
DHT1=1
DHT2=1
while [ $IDOT -le $NDOT ] ; do
  CURC=`echo $FILE | cut -d "." -f${IDOT}-${IDOT}`
  case "$CURC" in
    cam2 | cam | clm2 | pop | csim | cice | rtm )
      DCAS=`expr '(' $IDOT ')' '-' '1'`
      DVAR=`expr '(' $IDOT ')' '+' '1'`
      DHT1=$IDOT ;;
  esac
  IDOT=`expr '(' $IDOT ')' '+' '1'`
done
#
DCMP=$DHT1
COMP=`echo $FILE | cut -d"." -f${DCMP}`
#
DHT2=`expr '(' $DHT1 ')' '+' '1'`
DVAR=`expr '(' $DVAR ')' '+' '1'`
DTIM=`expr '(' $DVAR ')' '+' '1'`
#
CASES=`ls | egrep '\.[0-9][0-9][0-9][0-9]\.nc$' | cut -d"." -f1-${DCAS} | sort | uniq`
 VARS=`ls | egrep '\.[0-9][0-9][0-9][0-9]\.nc$' | cut -d"." -f${DVAR} | sort | uniq`
 HIST=`ls | egrep '\.[0-9][0-9][0-9][0-9]\.nc$' | cut -d"." -f${DHT1}-${DHT2} | sort | uniq`
 COMP=`ls | egrep '\.[0-9][0-9][0-9][0-9]\.nc$' | cut -d"." -f${DCMP} | sort | uniq`
#
for c in $CASES ; do
  for v in $VARS ; do
    CENS=`ls | egrep "${c}\.${HIST}\.${v}\.[0-9][0-9][0-9][0-9]\.nc" | cut -d"." -f${DTIM} | cut -c1-2 | sort | uniq`
    for d in $CENS ; do
      if [ "$d" == "08" ] || [ "$d" == "18" ] ; then
        GOOD=50
      else
        GOOD=100
      fi
      NUM=`ls ${c}.${HIST}.${v}.${d}??.nc | wc -l`
      if [ $NUM -eq $GOOD ] ; then
        if [ "$d" == "08" ] ; then
          Y0=0850
          Y1=0899
        else
          if [ "$d" == "18" ] ; then
            Y0=1800
            Y1=1849
          else
            Y0=${d}00
            Y1=${d}99
          fi
        fi
        case "$TPER" in
          ann )
           DF=CAT.${c}.${HIST}.${v}.${Y0}-${Y1}.nc ;;
          mon )
            DF=CAT.${c}.${HIST}.${v}.${Y0}01-${Y1}12.nc ;;
          day ) 
            DF=CAT.${c}.${HIST}.${v}.${Y0}0101-${Y1}1231.nc ;;
        esac
        echo -n "TS var_lme_year_to_cen of "${DF}" start: " ; date
        $NCRCAT -4 -L 1 -O ${c}.${HIST}.${v}.${d}??.nc $DF
        if [ $? = 0 ] ; then
          rm -f ${c}.${HIST}.${v}.${d}??.nc
          echo "Concatenated "$DF" and checked year count: "${GOOD}
          echo -n "TS var_lme_year_to_cen of "${DF}"   end: " ; date
        else
          echo "Failure on concat of "${c}"."${HIST}"."${v}" files"
          ./update_status error var_lme_year_to_cen
          exit 1
        fi
      else
        echo "Missing year(s) from "${c}"."${HIST}"."${v}"."${d}"??.nc files"
        echo "Count is "$NUM" should be "${GOOD}
        exit 1
      fi
    done
  done
done
