#!/bin/sh
#
# Concatenate decades of by-field CCSM netCDF into whole span
#
if [ $# -ne 0 ] ; then
  echo "Usage: var_mon_to_year"
  echo "Can use DECOUNT as defined by process_setup"
  exit 1
fi
# 
# Check for ncrcat
#
if [ ! $NCRCAT ] ; then
   TEST4NCRCAT=`which ncrcat 2<&1 >& /dev/null`
   if [ $? -eq 0 ] ; then
     NCRCAT=`which ncrcat`
   else
     echo "NCRCAT not in PATH - UNDEFINED"
     exit 1
   fi
fi
#
CHEK=`ls b*.*.h*.*.*cat*.nc | cut -d"." -f3 | cut -c1-2 | uniq`
for m in $CHEK ; do
  if [ $m = "ES" ] ; then
    FC=3 ; FV=6 ; FT=7 ; FD=4 ; FE=5
  else
    FC=2 ; FV=5 ; FT=6 ; FD=3 ; FE=4
  fi
  COMP=`ls b*.*.*.h*.*.*cat*.nc | cut -d"." -f${FD}-${FE} | uniq`
  for p in $COMP ; do
    VARS=`ls b*.*.${p}.*.*cat*.nc | cut -d"." -f${FV} | uniq`
    for v in $VARS ; do
      CASES=`ls b*.${p}.${v}.*cat*.nc | cut -d"." -f1-${FC} | uniq`
      for c in $CASES ; do
        if [ $DECOUNT ] ; then
          echo "Concatenating of "${c}"."${p}"."${v}" files and checking decade counts: "$DECOUNT
          if [ $p = "cam2.h1" ] ; then
            NUM=`ls ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc | wc -l`
            if [ $NUM = $DECOUNT ] ; then
              Y0=`ls ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc | head -1 | cut -d"." -f${FT} | cut -c1-4`
              Y1=`ls ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc | tail -1 | cut -d"." -f${FT} | cut -c16-19`
              DF=${c}.${p}.${v}.${Y0}-01-01_allcat_${Y1}-12-31.nc
              $NCRCAT -O ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc $DF
              if [ $? = 0 ] ; then
                rm -f ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc
                TF=${c}.${p}.${v}.${Y0}-01-01_cat_${Y1}-12-31.nc
                mv $DF $TF
                echo "Completed "$TF
              else
                echo "Failure on concat of "${c}"."${p}"."${v}" files"
                exit 1
              fi
            else
              echo "Missing decade(s) from "${c}"."${p}"."${v}" files"
              echo "Count is "$NUM" should be "$DECOUNT
              exit 1
            fi
          else
            NUM=`ls ${c}.${p}.${v}.????-01_cat_????-12.nc | wc -l`
            if [ $NUM = $DECOUNT ] ; then
              Y0=`ls ${c}.${p}.${v}.????-01_cat_????-12.nc | head -1 | cut -d"." -f${FT} | cut -c1-4`
              Y1=`ls ${c}.${p}.${v}.????-01_cat_????-12.nc | tail -1 | cut -d"." -f${FT} | cut -c13-16`
              DF=${c}.${p}.${v}.${Y0}-01-allcat_${Y1}-12.nc
              $NCRCAT -O ${c}.${p}.${v}.????-01_cat_????-12.nc $DF
              if [ $? = 0 ] ; then
                rm -f ${c}.${p}.${v}.????-01_cat_????-12.nc
                TF=${c}.${p}.${v}.${Y0}-01_cat_${Y1}-12.nc
                mv $DF $TF
                echo "Completed "$TF
              else
                echo "Failure on concat of "${c}"."${p}"."${v}" files"
                exit 1
              fi
            else
              echo "Missing decade(s) from "${c}"."${p}"."${v}" files"
              echo "Count is "$NUM" should be "$DECOUNT
              exit 1
            fi
          fi
        else
          echo "Concatenating of "${c}"."${p}"."${v}" files WITHOUT checking counts." 
          if [ $p = "cam2.h1" ] ; then
            Y0=`ls ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc | head -1 | cut -d"." -f${FT} | cut -c1-4`
            Y1=`ls ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc | tail -1 | cut -d"." -f${FT} | cut -c16-19`
            DF=${c}.${p}.${v}.${Y0}-01-01_allcat_${Y1}-12-31.nc
            $NCRCAT -O ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc $DF
            if [ $? = 0 ] ; then
              rm -f ${c}.${p}.${v}.????-01-01_cat_????-12-31.nc
              TF=${c}.${p}.${v}.${Y0}-01-01_cat_${Y1}-12-31.nc
              mv $DF $TF
              echo "Completed "$TF
            else
              echo "Failure on concat of "${c}"."${p}"."${v}" files"
              exit 1
            fi
          else
            Y0=`ls ${c}.${p}.${v}.????-01_cat_????-12.nc | head -1 | cut -d"." -f${FT} | cut -c1-4`
            Y1=`ls ${c}.${p}.${v}.????-01_cat_????-12.nc | tail -1 | cut -d"." -f${FT} | cut -c13-16`
            DF=${c}.${p}.${v}.${Y0}-01_allcat_${Y1}-12.nc
            $NCRCAT -O ${c}.${p}.${v}.????-01_cat_????-12.nc ${DF}
            if [ $? = 0 ] ; then
              rm -f ${c}.${p}.${v}.????-01_cat_????-12.nc
              TF=${c}.${p}.${v}.${Y0}-01_cat_${Y1}-12.nc
              mv $DF $TF
              echo "Completed "$TF
            else
              echo "Failure on concat of "${c}"."${p}"."${v}" files"
              exit 1
            fi
          fi
        fi
      done
    done
  done
done
