#!/bin/sh
#
# Concatenate months of by-field netCDF files into years
#
if [ $# -ne 0 ] ; then
  echo "Usage: var_mon_to_year"
  exit 1
fi
# 
# Check for ncrcat
#
if [ ! $NCRCAT ] ; then
   TEST4NCRCAT=`which ncrcat 2<&1 >& /dev/null`
   if [ $? -eq 0 ] ; then
     NCRCAT=`which ncrcat`
   else
     echo "NCRCAT not in PATH - UNDEFINED"
     exit 1
   fi
fi
#
KIND=`ls *.????-??.nc | cut -c1-1 | uniq`
if [ $KIND = "b" ] ; then
  CHEK=`ls b*.????-??.nc | cut -d"." -f3 | cut -c1-2 | uniq`
  if [ $m = "ES" ] ; then
    FC=3 ; FV=6 ; FT=7 ; FD=4 ; FE=5
  else
    FC=2 ; FV=5 ; FT=6 ; FD=3 ; FE=4
  fi
else
    FC=1 ; FV=4 ; FT=5 ; FD=2 ; FE=3
fi
#
COMP=`ls *.????-??.nc | cut -d"." -f${FD}-${FE} | uniq`
for p in $COMP ; do
  VARS=`ls *.${p}.*.????-??.nc | cut -d"." -f${FV} | uniq`
  for v in $VARS ; do
    CASES=`ls *.${p}.${v}.????-??.nc | cut -d"." -f1-${FC} | uniq`
    for c in $CASES ; do      
      YEARS=`ls ${c}.${p}.${v}.????-??.nc | cut -d"." -f${FT} | cut -c1-4 | uniq`
      for y in $YEARS ; do
        NUM=`ls ${c}.${p}.${v}.${y}-??.nc | wc -l`
        if [ $NUM -eq 12 ] ; then
          DF=${c}.${p}.${v}.${y}.nc
          if [ $DF ] ; then
            $NCRCAT -O ${c}.${p}.${v}.${y}-??.nc $DF
            if [ $? -eq 0 ] ; then
              rm -f ${c}.${p}.${v}.${y}-??.nc
            fi
          else
            echo "Undefined DF: "$DF
            exit 1
          fi
        fi
      done
    done
  done
done
