#!/bin/sh 
#
# Run3hr
#
if [ $# -eq 0 ] ; then
   echo 'Usage: Run3hr case comp "CMIP5 fields"'
   echo ""
   echo "  case is required"
   echo "  comp is required"
   echo '  "CMIP5_fields" is optional - if not given, then all fields in xwalk will be processed'
   echo "   Otherwise, blank-delimited list inside double quotes, example:"
   echo ""
   echo '   ./Run3hr b40.20th.track1.deg.008 cam2.h0 "tas ta pr"'
   exit 1
elif [ $# -eq 2 ] ; then
   CASE=$1
   COMP=$2
elif [ $# -eq 3 ] ; then
   CASE=$1
   COMP=$2
   VARS=$3
else
   echo 'Usage: Run3hr case comp "CMIP5 fields"'
   echo ""
   echo "  case is required"
   echo "  comp is required"
   echo '  "CMIP5_fields" is optional - if not given, then all fields in xwalk will be processed'
   echo "   Otherwise, blank-delimited list inside double quotes, example:"
   echo ""
   echo '   ./Run3hr b40.20th.track1.deg.008 cam2.h0 "tas ta pr"'
fi
#
BASED=${HOME}/CCP_Processing_Suite
CMORD=${HOME}/CCP_Processing_Suite/CMOR2
CBIND=${HOME}/bin
#
XWALK=xwalk_3hr.txt
#
ln -s -f ${BASED}/experiments.txt           .
ln -s -f ${CMORD}/Tables                    .
ln -s -f ${CMORD}/GridFiles/atm_grid_f09.nc .
#
# Assume all fields in xwalk to be processed
#
if [ $# -eq 2 ] ; then
  echo "Linking "${CMORD}"/"${XWALK}
  ln -s -f ${CMORD}/${XWALK} .
fi
#
# Create new xwalk file containing just the fields to be processed
#
if [ $# -eq 3 ] ; then
  echo "Creating new xwalk file from default "${XWALK}
  rm -f ${XWALK}
  for ivar in `echo $VARS` ; do
    egrep ":${ivar}:" ${CMORD}/${XWALK} >> ${XWALK} 
    echo $ivar" added to "${XWALK}
  done
fi
#
# Do it!
#
rm -f 3hr_in.${CASE}.${COMP} Info_in.${CASE}.${COMP}
if [ ! -d ./CMOR ] ; then
  mkdir ./CMOR
fi
#
echo $CASE >> 3hr_in.${CASE}.${COMP}
echo $COMP >> 3hr_in.${CASE}.${COMP}
#
# Set up various tracking information to be read in and made global metadata
#
WHOAMI=`whoami`
PRCHST=`hostname`
SVNBIN=`which svn`
SVNREV=`$SVNBIN info $SVN | egrep "Rev:"`
SVNDAT=`$SVNBIN info $SVN | egrep "Date:"`
SVNUID=`$SVNBIN info $SVN | egrep "UUID:"`
echo $WHOAMI >> Info_in.${CASE}.${COMP}
echo $PRCHST >> Info_in.${CASE}.${COMP}
echo $SVNREV >> Info_in.${CASE}.${COMP}
echo $SVNDAT >> Info_in.${CASE}.${COMP}
echo $SVNUID >> Info_in.${CASE}.${COMP}
#
if [ -f ${CBIND}/3hr_CMOR ] ; then
  ln -s -f ${CBIND}/3hr_CMOR .
else
  echo "3hr_CMOR NOT FOUND in "${CBIND}". Rebuild."
  exit 1
fi
#
cat 3hr_in.${CASE}.${COMP} | ./3hr_CMOR
#
#rm -f 3hr_in.${CASE}.${COMP}
