#!/bin/sh 
#
if [ $# -eq 0 ] ; then
   echo "Usage: RunAmon case comp"
   exit 1
elif [ $# -eq 2 ] ; then
   CASE=$1
   COMP=$2
else
   echo "Usage: RunAmon case comp"
   exit 1
fi
#
if [ ! -d ./CMOR ] ; then
  mkdir ./CMOR
fi
#
ln -s -f ${HOME}/CCP_Processing_Suite/experiments.txt       .
ln -s -f ${HOME}/CCP_Processing_Suite/CMOR2/Tables          .
ln -s -f ${HOME}/CCP_Processing_Suite/CMOR2/xwalk_Amon.txt  .
ln -s -f ${HOME}/CCP_Processing_Suite/CMOR2/atm_grid_f09.nc .
#
rm -f Amon_in.${CASE}.${COMP} Info_in.${CASE}.${COMP}
#
echo $CASE >> Amon_in.${CASE}.${COMP}
echo $COMP >> Amon_in.${CASE}.${COMP}
#
# Set up various tracking information to be read in and made global metadata
#
WHOAMI=`whoami`
SVNREV=`svn info $SVN | egrep "Rev:"`
SVNDAT=`svn info $SVN | egrep "Date:"`
SVNUID=`svn info $SVN | egrep "UUID:"`
echo $WHOAMI >> Info_in.${CASE}.${COMP}
echo $SVNREV >> Info_in.${CASE}.${COMP}
echo $SVNDAT >> Info_in.${CASE}.${COMP}
echo $SVNUID >> Info_in.${CASE}.${COMP}
cat Info_in.${CASE}.${COMP}
cat Amon_in.${CASE}.${COMP} | Amon_CMOR
#
#rm -f Amon_in.${CASE}.${COMP}
